;; Generated by :claw at 2021-10-10T13:44:32.670387Z
(uiop:define-package :%al.ext (:use))
(uiop:define-package :aw-openal-ext-bindings~pristine (:use :cl))
(common-lisp:in-package :aw-openal-ext-bindings~pristine)

(defparameter %al.ext::+5point1+ 5380)

(defparameter %al.ext::+6point1+ 5381)

(defparameter %al.ext::+7point1+ 5382)

(defparameter %al.ext::+acn+ 1)

(defparameter %al.ext::+ambisonic-layout+ 6551)

(defparameter %al.ext::+ambisonic-order+ 6553)

(defparameter %al.ext::+ambisonic-scaling+ 6552)

(defparameter %al.ext::+bformat3d+ 5383)

(defparameter %al.ext::+byte+ 5120)

(defparameter %al.ext::+chan-cd-loki+ 5242883)

(defparameter %al.ext::+chan-main-loki+ 5242881)

(defparameter %al.ext::+chan-pcm-loki+ 5242882)

(defparameter %al.ext::+connected+ 787)

(defparameter %al.ext::+default-filter-order+ 4352)

(defparameter %al.ext::+device-clock-latency+ 5634)

(defparameter %al.ext::+device-clock+ 5632)

(defparameter %al.ext::+device-latency+ 5633)

(defparameter %al.ext::+dont-care+ 2)

(defparameter %al.ext::+major-version+ 131073)

(defparameter %al.ext::+minor-version+ 131074)

(defparameter %al.ext::+ext-dedicated+ 1)

(defparameter %al.ext::+ext-default-filter-order+ 1)

(defparameter %al.ext::+ext-efx+ 1)

(defparameter %al.ext::+ext-efx-name+ "ALC_EXT_EFX")

(defparameter %al.ext::+ext-disconnect+ 1)

(defparameter %al.ext::+ext-thread-local-context+ 1)

(defparameter %al.ext::+float+ 5126)

(defparameter %al.ext::+format-channels+ 6544)

(defparameter %al.ext::+format-type+ 6545)

(defparameter %al.ext::+fuma+ 0)

(defparameter %al.ext::+hrtf-denied+ 2)

(defparameter %al.ext::+hrtf-disabled+ 0)

(defparameter %al.ext::+hrtf-enabled+ 1)

(defparameter %al.ext::+hrtf-headphones-detected+ 4)

(defparameter %al.ext::+hrtf-id+ 6550)

(defparameter %al.ext::+hrtf-required+ 3)

(defparameter %al.ext::+hrtf+ 6546)

(defparameter %al.ext::+hrtf-specifier+ 6549)

(defparameter %al.ext::+hrtf-status+ 6547)

(defparameter %al.ext::+hrtf-unsupported-format+ 5)

(defparameter %al.ext::+int+ 5124)

(defparameter %al.ext::+loki-audio-channel+ 1)

(defparameter %al.ext::+max-ambisonic-order+ 6555)

(defparameter %al.ext::+max-auxiliary-sends+ 131075)

(defparameter %al.ext::+mono+ 5376)

(defparameter %al.ext::+n3d+ 2)

(defparameter %al.ext::+num-hrtf-specifiers+ 6548)

(defparameter %al.ext::+output-limiter+ 6554)

(defparameter %al.ext::+quad+ 5379)

(defparameter %al.ext::+short+ 5122)

(defparameter %al.ext::+sn3d+ 1)

(defparameter %al.ext::+soft-hrtf+ 1)

(defparameter %al.ext::+soft-device-clock+ 1)

(defparameter %al.ext::+soft-loopback+ 1)

(defparameter %al.ext::+soft-loopback-bformat+ 1)

(defparameter %al.ext::+soft-output-limiter+ nil)

(defparameter %al.ext::+soft-pause-device+ 1)

(defparameter %al.ext::+stereo+ 5377)

(defparameter %al.ext::+unsigned-byte+ 5121)

(defparameter %al.ext::+unsigned-int+ 5125)

(defparameter %al.ext::+unsigned-short+ 5123)

(defparameter %al.ext::+5point1-16+ 4619)

(defparameter %al.ext::+5point1-32f+ 4620)

(defparameter %al.ext::+5point1-8+ 4618)

(defparameter %al.ext::+5point1+ 5380)

(defparameter %al.ext::+6point1-16+ 4622)

(defparameter %al.ext::+6point1-32f+ 4623)

(defparameter %al.ext::+6point1-8+ 4621)

(defparameter %al.ext::+6point1+ 5381)

(defparameter %al.ext::+7point1-16+ 4625)

(defparameter %al.ext::+7point1-32f+ 4626)

(defparameter %al.ext::+7point1-8+ 4624)

(defparameter %al.ext::+7point1+ 5382)

(defparameter %al.ext::+acn+ 1)

(defparameter %al.ext::+air-absorption-factor+ 131079)

(defparameter %al.ext::+ext-h+ nil)

(defparameter %al.ext::+ext-prototypes+ 1)

(defparameter %al.ext::+ambisonic-layout+ 6551)

(defparameter %al.ext::+ambisonic-scaling+ 6552)

(defparameter %al.ext::+autowah-attack-time+ 1)

(defparameter %al.ext::+autowah-default-attack-time+ 0.05999999865889549D0)

(defparameter %al.ext::+autowah-default-peak-gain+ 11.220000267028809D0)

(defparameter %al.ext::+autowah-default-release-time+ 0.05999999865889549D0)

(defparameter %al.ext::+autowah-default-resonance+ 1000.0D0)

(defparameter %al.ext::+autowah-max-attack-time+ 1.0D0)

(defparameter %al.ext::+autowah-max-peak-gain+ 31621.0D0)

(defparameter %al.ext::+autowah-max-release-time+ 1.0D0)

(defparameter %al.ext::+autowah-max-resonance+ 1000.0D0)

(defparameter %al.ext::+autowah-min-attack-time+ 9.999999747378752D-5)

(defparameter %al.ext::+autowah-min-peak-gain+ 2.9999999242136255D-5)

(defparameter %al.ext::+autowah-min-release-time+ 9.999999747378752D-5)

(defparameter %al.ext::+autowah-min-resonance+ 2.0D0)

(defparameter %al.ext::+autowah-peak-gain+ 4)

(defparameter %al.ext::+autowah-release-time+ 2)

(defparameter %al.ext::+autowah-resonance+ 3)

(defparameter %al.ext::+auto+ 2)

(defparameter %al.ext::+auxiliary-send-filter+ 131078)

(defparameter %al.ext::+auxiliary-send-filter-gainhf-auto+ 131084)

(defparameter %al.ext::+auxiliary-send-filter-gain-auto+ 131083)

(defparameter %al.ext::+bandpass-default-gain+ 1.0D0)

(defparameter %al.ext::+bandpass-default-gainhf+ 1.0D0)

(defparameter %al.ext::+bandpass-default-gainlf+ 1.0D0)

(defparameter %al.ext::+bandpass-gain+ 1)

(defparameter %al.ext::+bandpass-gainhf+ 3)

(defparameter %al.ext::+bandpass-gainlf+ 2)

(defparameter %al.ext::+bandpass-max-gain+ 1.0D0)

(defparameter %al.ext::+bandpass-max-gainhf+ 1.0D0)

(defparameter %al.ext::+bandpass-max-gainlf+ 1.0D0)

(defparameter %al.ext::+bandpass-min-gain+ 0.0D0)

(defparameter %al.ext::+bandpass-min-gainhf+ 0.0D0)

(defparameter %al.ext::+bandpass-min-gainlf+ 0.0D0)

(defparameter %al.ext::+byte3+ 5128)

(defparameter %al.ext::+byte-length+ 8201)

(defparameter %al.ext::+byte-rw-offsets+ 4145)

(defparameter %al.ext::+byte+ 5120)

(defparameter %al.ext::+chorus-default-delay+ 0.01600000075995922D0)

(defparameter %al.ext::+chorus-default-depth+ 0.10000000149011612D0)

(defparameter %al.ext::+chorus-default-feedback+ 0.25D0)

(defparameter %al.ext::+chorus-default-phase+ 90)

(defparameter %al.ext::+chorus-default-rate+ 1.100000023841858D0)

(defparameter %al.ext::+chorus-default-waveform+ 1)

(defparameter %al.ext::+chorus-delay+ 6)

(defparameter %al.ext::+chorus-depth+ 4)

(defparameter %al.ext::+chorus-feedback+ 5)

(defparameter %al.ext::+chorus-max-delay+ 0.01600000075995922D0)

(defparameter %al.ext::+chorus-max-depth+ 1.0D0)

(defparameter %al.ext::+chorus-max-feedback+ 1.0D0)

(defparameter %al.ext::+chorus-max-phase+ 180)

(defparameter %al.ext::+chorus-max-rate+ 10.0D0)

(defparameter %al.ext::+chorus-max-waveform+ 1)

(defparameter %al.ext::+chorus-min-delay+ 0.0D0)

(defparameter %al.ext::+chorus-min-depth+ 0.0D0)

(defparameter %al.ext::+chorus-min-feedback+ -1.0D0)

(defparameter %al.ext::+chorus-min-phase+ -180)

(defparameter %al.ext::+chorus-min-rate+ 0.0D0)

(defparameter %al.ext::+chorus-min-waveform+ 0)

(defparameter %al.ext::+chorus-phase+ 2)

(defparameter %al.ext::+chorus-rate+ 3)

(defparameter %al.ext::+chorus-waveform+ 1)

(defparameter %al.ext::+chorus-waveform-sinusoid+ 0)

(defparameter %al.ext::+chorus-waveform-triangle+ 1)

(defparameter %al.ext::+compressor-default-onoff+ 1)

(defparameter %al.ext::+compressor-max-onoff+ 1)

(defparameter %al.ext::+compressor-min-onoff+ 0)

(defparameter %al.ext::+compressor-onoff+ 1)

(defparameter %al.ext::+cone-outer-gainhf+ 131081)

(defparameter %al.ext::+dedicated-gain+ 1)

(defparameter %al.ext::+default-air-absorption-factor+ 0.0D0)

(defparameter %al.ext::+default-auxiliary-send-filter-gainhf-auto+ 1)

(defparameter %al.ext::+default-auxiliary-send-filter-gain-auto+ 1)

(defparameter %al.ext::+default-cone-outer-gainhf+ 1.0D0)

(defparameter %al.ext::+default-direct-filter-gainhf-auto+ 1)

(defparameter %al.ext::+default-meters-per-unit+ 1.0D0)

(defparameter %al.ext::+default-resampler+ 4625)

(defparameter %al.ext::+default-room-rolloff-factor+ 0.0D0)

(defparameter %al.ext::+deferred-updates+ 49154)

(defparameter %al.ext::+direct-channels+ 4147)

(defparameter %al.ext::+direct-filter+ 131077)

(defparameter %al.ext::+direct-filter-gainhf-auto+ 131082)

(defparameter %al.ext::+distortion-default-edge+ 0.20000000298023224D0)

(defparameter %al.ext::+distortion-default-eqbandwidth+ 3600.0D0)

(defparameter %al.ext::+distortion-default-eqcenter+ 3600.0D0)

(defparameter %al.ext::+distortion-default-gain+ 0.05000000074505806D0)

(defparameter %al.ext::+distortion-default-lowpass-cutoff+ 8000.0D0)

(defparameter %al.ext::+distortion-edge+ 1)

(defparameter %al.ext::+distortion-eqbandwidth+ 5)

(defparameter %al.ext::+distortion-eqcenter+ 4)

(defparameter %al.ext::+distortion-gain+ 2)

(defparameter %al.ext::+distortion-lowpass-cutoff+ 3)

(defparameter %al.ext::+distortion-max-edge+ 1.0D0)

(defparameter %al.ext::+distortion-max-eqbandwidth+ 24000.0D0)

(defparameter %al.ext::+distortion-max-eqcenter+ 24000.0D0)

(defparameter %al.ext::+distortion-max-gain+ 1.0D0)

(defparameter %al.ext::+distortion-max-lowpass-cutoff+ 24000.0D0)

(defparameter %al.ext::+distortion-min-edge+ 0.0D0)

(defparameter %al.ext::+distortion-min-eqbandwidth+ 80.0D0)

(defparameter %al.ext::+distortion-min-eqcenter+ 80.0D0)

(defparameter %al.ext::+distortion-min-gain+ 0.009999999776482582D0)

(defparameter %al.ext::+distortion-min-lowpass-cutoff+ 80.0D0)

(defparameter %al.ext::+double+ 5127)

(defparameter %al.ext::+drop-unmatched+ 1)

(defparameter %al.ext::+eaxreverb-air-absorption-gainhf+ 19)

(defparameter %al.ext::+eaxreverb-decay-hflimit+ 23)

(defparameter %al.ext::+eaxreverb-decay-hfratio+ 7)

(defparameter %al.ext::+eaxreverb-decay-lfratio+ 8)

(defparameter %al.ext::+eaxreverb-decay-time+ 6)

(defparameter %al.ext::+eaxreverb-default-air-absorption-gainhf+ 0.9940000176429749D0)

(defparameter %al.ext::+eaxreverb-default-decay-hflimit+ 1)

(defparameter %al.ext::+eaxreverb-default-decay-hfratio+ 0.8299999833106995D0)

(defparameter %al.ext::+eaxreverb-default-decay-lfratio+ 1.0D0)

(defparameter %al.ext::+eaxreverb-default-decay-time+ 1.4900000095367432D0)

(defparameter %al.ext::+eaxreverb-default-density+ 1.0D0)

(defparameter %al.ext::+eaxreverb-default-diffusion+ 1.0D0)

(defparameter %al.ext::+eaxreverb-default-echo-depth+ 0.0D0)

(defparameter %al.ext::+eaxreverb-default-echo-time+ 0.25D0)

(defparameter %al.ext::+eaxreverb-default-gain+ 0.3199999928474426D0)

(defparameter %al.ext::+eaxreverb-default-gainhf+ 0.8899999856948853D0)

(defparameter %al.ext::+eaxreverb-default-gainlf+ 1.0D0)

(defparameter %al.ext::+eaxreverb-default-hfreference+ 5000.0D0)

(defparameter %al.ext::+eaxreverb-default-late-reverb-delay+ 0.010999999940395355D0)

(defparameter %al.ext::+eaxreverb-default-late-reverb-gain+ 1.2599999904632568D0)

(defparameter %al.ext::+eaxreverb-default-late-reverb-pan-xyz+ 0.0D0)

(defparameter %al.ext::+eaxreverb-default-lfreference+ 250.0D0)

(defparameter %al.ext::+eaxreverb-default-modulation-depth+ 0.0D0)

(defparameter %al.ext::+eaxreverb-default-modulation-time+ 0.25D0)

(defparameter %al.ext::+eaxreverb-default-reflections-delay+ 0.007000000216066837D0)

(defparameter %al.ext::+eaxreverb-default-reflections-gain+ 0.05000000074505806D0)

(defparameter %al.ext::+eaxreverb-default-reflections-pan-xyz+ 0.0D0)

(defparameter %al.ext::+eaxreverb-default-room-rolloff-factor+ 0.0D0)

(defparameter %al.ext::+eaxreverb-density+ 1)

(defparameter %al.ext::+eaxreverb-diffusion+ 2)

(defparameter %al.ext::+eaxreverb-echo-depth+ 16)

(defparameter %al.ext::+eaxreverb-echo-time+ 15)

(defparameter %al.ext::+eaxreverb-gain+ 3)

(defparameter %al.ext::+eaxreverb-gainhf+ 4)

(defparameter %al.ext::+eaxreverb-gainlf+ 5)

(defparameter %al.ext::+eaxreverb-hfreference+ 20)

(defparameter %al.ext::+eaxreverb-late-reverb-delay+ 13)

(defparameter %al.ext::+eaxreverb-late-reverb-gain+ 12)

(defparameter %al.ext::+eaxreverb-late-reverb-pan+ 14)

(defparameter %al.ext::+eaxreverb-lfreference+ 21)

(defparameter %al.ext::+eaxreverb-max-air-absorption-gainhf+ 1.0D0)

(defparameter %al.ext::+eaxreverb-max-decay-hflimit+ 1)

(defparameter %al.ext::+eaxreverb-max-decay-hfratio+ 2.0D0)

(defparameter %al.ext::+eaxreverb-max-decay-lfratio+ 2.0D0)

(defparameter %al.ext::+eaxreverb-max-decay-time+ 20.0D0)

(defparameter %al.ext::+eaxreverb-max-density+ 1.0D0)

(defparameter %al.ext::+eaxreverb-max-diffusion+ 1.0D0)

(defparameter %al.ext::+eaxreverb-max-echo-depth+ 1.0D0)

(defparameter %al.ext::+eaxreverb-max-echo-time+ 0.25D0)

(defparameter %al.ext::+eaxreverb-max-gain+ 1.0D0)

(defparameter %al.ext::+eaxreverb-max-gainhf+ 1.0D0)

(defparameter %al.ext::+eaxreverb-max-gainlf+ 1.0D0)

(defparameter %al.ext::+eaxreverb-max-hfreference+ 20000.0D0)

(defparameter %al.ext::+eaxreverb-max-late-reverb-delay+ 0.10000000149011612D0)

(defparameter %al.ext::+eaxreverb-max-late-reverb-gain+ 10.0D0)

(defparameter %al.ext::+eaxreverb-max-lfreference+ 1000.0D0)

(defparameter %al.ext::+eaxreverb-max-modulation-depth+ 1.0D0)

(defparameter %al.ext::+eaxreverb-max-modulation-time+ 4.0D0)

(defparameter %al.ext::+eaxreverb-max-reflections-delay+ 0.30000001192092896D0)

(defparameter %al.ext::+eaxreverb-max-reflections-gain+ 3.1600000858306885D0)

(defparameter %al.ext::+eaxreverb-max-room-rolloff-factor+ 10.0D0)

(defparameter %al.ext::+eaxreverb-min-air-absorption-gainhf+ 0.8920000195503235D0)

(defparameter %al.ext::+eaxreverb-min-decay-hflimit+ 0)

(defparameter %al.ext::+eaxreverb-min-decay-hfratio+ 0.10000000149011612D0)

(defparameter %al.ext::+eaxreverb-min-decay-lfratio+ 0.10000000149011612D0)

(defparameter %al.ext::+eaxreverb-min-decay-time+ 0.10000000149011612D0)

(defparameter %al.ext::+eaxreverb-min-density+ 0.0D0)

(defparameter %al.ext::+eaxreverb-min-diffusion+ 0.0D0)

(defparameter %al.ext::+eaxreverb-min-echo-depth+ 0.0D0)

(defparameter %al.ext::+eaxreverb-min-echo-time+ 0.07500000298023224D0)

(defparameter %al.ext::+eaxreverb-min-gain+ 0.0D0)

(defparameter %al.ext::+eaxreverb-min-gainhf+ 0.0D0)

(defparameter %al.ext::+eaxreverb-min-gainlf+ 0.0D0)

(defparameter %al.ext::+eaxreverb-min-hfreference+ 1000.0D0)

(defparameter %al.ext::+eaxreverb-min-late-reverb-delay+ 0.0D0)

(defparameter %al.ext::+eaxreverb-min-late-reverb-gain+ 0.0D0)

(defparameter %al.ext::+eaxreverb-min-lfreference+ 20.0D0)

(defparameter %al.ext::+eaxreverb-min-modulation-depth+ 0.0D0)

(defparameter %al.ext::+eaxreverb-min-modulation-time+ 0.03999999910593033D0)

(defparameter %al.ext::+eaxreverb-min-reflections-delay+ 0.0D0)

(defparameter %al.ext::+eaxreverb-min-reflections-gain+ 0.0D0)

(defparameter %al.ext::+eaxreverb-min-room-rolloff-factor+ 0.0D0)

(defparameter %al.ext::+eaxreverb-modulation-depth+ 18)

(defparameter %al.ext::+eaxreverb-modulation-time+ 17)

(defparameter %al.ext::+eaxreverb-reflections-delay+ 10)

(defparameter %al.ext::+eaxreverb-reflections-gain+ 9)

(defparameter %al.ext::+eaxreverb-reflections-pan+ 11)

(defparameter %al.ext::+eaxreverb-room-rolloff-factor+ 22)

(defparameter %al.ext::+echo-damping+ 3)

(defparameter %al.ext::+echo-default-damping+ 0.5D0)

(defparameter %al.ext::+echo-default-delay+ 0.10000000149011612D0)

(defparameter %al.ext::+echo-default-feedback+ 0.5D0)

(defparameter %al.ext::+echo-default-lrdelay+ 0.10000000149011612D0)

(defparameter %al.ext::+echo-default-spread+ -1.0D0)

(defparameter %al.ext::+echo-delay+ 1)

(defparameter %al.ext::+echo-feedback+ 4)

(defparameter %al.ext::+echo-lrdelay+ 2)

(defparameter %al.ext::+echo-max-damping+ 0.9900000095367432D0)

(defparameter %al.ext::+echo-max-delay+ 0.2070000022649765D0)

(defparameter %al.ext::+echo-max-feedback+ 1.0D0)

(defparameter %al.ext::+echo-max-lrdelay+ 0.40400001406669617D0)

(defparameter %al.ext::+echo-max-spread+ 1.0D0)

(defparameter %al.ext::+echo-min-damping+ 0.0D0)

(defparameter %al.ext::+echo-min-delay+ 0.0D0)

(defparameter %al.ext::+echo-min-feedback+ 0.0D0)

(defparameter %al.ext::+echo-min-lrdelay+ 0.0D0)

(defparameter %al.ext::+echo-min-spread+ -1.0D0)

(defparameter %al.ext::+echo-spread+ 5)

(defparameter %al.ext::+effectslot-auxiliary-send-auto+ 3)

(defparameter %al.ext::+effectslot-effect+ 1)

(defparameter %al.ext::+effectslot-gain+ 2)

(defparameter %al.ext::+effectslot-null+ 0)

(defparameter %al.ext::+effectslot-target+ 6556)

(defparameter %al.ext::+effect-autowah+ 10)

(defparameter %al.ext::+effect-chorus+ 2)

(defparameter %al.ext::+effect-compressor+ 11)

(defparameter %al.ext::+effect-dedicated-dialogue+ 36865)

(defparameter %al.ext::+effect-dedicated-low-frequency-effect+ 36864)

(defparameter %al.ext::+effect-distortion+ 3)

(defparameter %al.ext::+effect-eaxreverb+ 32768)

(defparameter %al.ext::+effect-echo+ 4)

(defparameter %al.ext::+effect-equalizer+ 12)

(defparameter %al.ext::+effect-first-parameter+ 0)

(defparameter %al.ext::+effect-flanger+ 5)

(defparameter %al.ext::+effect-frequency-shifter+ 6)

(defparameter %al.ext::+effect-last-parameter+ 32768)

(defparameter %al.ext::+effect-null+ 0)

(defparameter %al.ext::+effect-pitch-shifter+ 8)

(defparameter %al.ext::+effect-reverb+ 1)

(defparameter %al.ext::+effect-ring-modulator+ 9)

(defparameter %al.ext::+effect-type+ 32769)

(defparameter %al.ext::+effect-vocal-morpher+ 7)

(defparameter %al.ext::+%h+ nil)

(defparameter %al.ext::+equalizer-default-high-cutoff+ 6000.0D0)

(defparameter %al.ext::+equalizer-default-high-gain+ 1.0D0)

(defparameter %al.ext::+equalizer-default-low-cutoff+ 200.0D0)

(defparameter %al.ext::+equalizer-default-low-gain+ 1.0D0)

(defparameter %al.ext::+equalizer-default-mid1-center+ 500.0D0)

(defparameter %al.ext::+equalizer-default-mid1-gain+ 1.0D0)

(defparameter %al.ext::+equalizer-default-mid1-width+ 1.0D0)

(defparameter %al.ext::+equalizer-default-mid2-center+ 3000.0D0)

(defparameter %al.ext::+equalizer-default-mid2-gain+ 1.0D0)

(defparameter %al.ext::+equalizer-default-mid2-width+ 1.0D0)

(defparameter %al.ext::+equalizer-high-cutoff+ 10)

(defparameter %al.ext::+equalizer-high-gain+ 9)

(defparameter %al.ext::+equalizer-low-cutoff+ 2)

(defparameter %al.ext::+equalizer-low-gain+ 1)

(defparameter %al.ext::+equalizer-max-high-cutoff+ 16000.0D0)

(defparameter %al.ext::+equalizer-max-high-gain+ 7.942999839782715D0)

(defparameter %al.ext::+equalizer-max-low-cutoff+ 800.0D0)

(defparameter %al.ext::+equalizer-max-low-gain+ 7.942999839782715D0)

(defparameter %al.ext::+equalizer-max-mid1-center+ 3000.0D0)

(defparameter %al.ext::+equalizer-max-mid1-gain+ 7.942999839782715D0)

(defparameter %al.ext::+equalizer-max-mid1-width+ 1.0D0)

(defparameter %al.ext::+equalizer-max-mid2-center+ 8000.0D0)

(defparameter %al.ext::+equalizer-max-mid2-gain+ 7.942999839782715D0)

(defparameter %al.ext::+equalizer-max-mid2-width+ 1.0D0)

(defparameter %al.ext::+equalizer-mid1-center+ 4)

(defparameter %al.ext::+equalizer-mid1-gain+ 3)

(defparameter %al.ext::+equalizer-mid1-width+ 5)

(defparameter %al.ext::+equalizer-mid2-center+ 7)

(defparameter %al.ext::+equalizer-mid2-gain+ 6)

(defparameter %al.ext::+equalizer-mid2-width+ 8)

(defparameter %al.ext::+equalizer-min-high-cutoff+ 4000.0D0)

(defparameter %al.ext::+equalizer-min-high-gain+ 0.12600000202655792D0)

(defparameter %al.ext::+equalizer-min-low-cutoff+ 50.0D0)

(defparameter %al.ext::+equalizer-min-low-gain+ 0.12600000202655792D0)

(defparameter %al.ext::+equalizer-min-mid1-center+ 200.0D0)

(defparameter %al.ext::+equalizer-min-mid1-gain+ 0.12600000202655792D0)

(defparameter %al.ext::+equalizer-min-mid1-width+ 0.009999999776482582D0)

(defparameter %al.ext::+equalizer-min-mid2-center+ 1000.0D0)

(defparameter %al.ext::+equalizer-min-mid2-gain+ 0.12600000202655792D0)

(defparameter %al.ext::+equalizer-min-mid2-width+ 0.009999999776482582D0)

(defparameter %al.ext::+event-callback-function+ 6562)

(defparameter %al.ext::+event-callback-user-param+ 6563)

(defparameter %al.ext::+event-type-buffer-completed+ 6564)

(defparameter %al.ext::+event-type-disconnected+ 6566)

(defparameter %al.ext::+event-type-source-state-changed+ 6565)

(defparameter %al.ext::+ext-alaw+ 1)

(defparameter %al.ext::+ext-bformat+ 1)

(defparameter %al.ext::+ext-foldback+ 1)

(defparameter %al.ext::+ext-foldback-name+ "AL_EXT_FOLDBACK")

(defparameter %al.ext::+ext-ima4+ 1)

(defparameter %al.ext::+ext-mcformats+ 1)

(defparameter %al.ext::+ext-mulaw+ 1)

(defparameter %al.ext::+ext-mulaw-bformat+ 1)

(defparameter %al.ext::+ext-mulaw-mcformats+ 1)

(defparameter %al.ext::+ext-source-radius+ 1)

(defparameter %al.ext::+ext-static-buffer+ 1)

(defparameter %al.ext::+ext-stereo-angles+ 1)

(defparameter %al.ext::+ext-double+ 1)

(defparameter %al.ext::+ext-float32+ 1)

(defparameter %al.ext::+ext-source-distance-model+ 1)

(defparameter %al.ext::+ext-vorbis+ 1)

(defparameter %al.ext::+filter-bandpass+ 3)

(defparameter %al.ext::+filter-first-parameter+ 0)

(defparameter %al.ext::+filter-highpass+ 2)

(defparameter %al.ext::+filter-last-parameter+ 32768)

(defparameter %al.ext::+filter-lowpass+ 1)

(defparameter %al.ext::+filter-null+ 0)

(defparameter %al.ext::+filter-type+ 32769)

(defparameter %al.ext::+flanger-default-delay+ 0.0020000000949949026D0)

(defparameter %al.ext::+flanger-default-depth+ 1.0D0)

(defparameter %al.ext::+flanger-default-feedback+ -0.5D0)

(defparameter %al.ext::+flanger-default-phase+ 0)

(defparameter %al.ext::+flanger-default-rate+ 0.27000001072883606D0)

(defparameter %al.ext::+flanger-default-waveform+ 1)

(defparameter %al.ext::+flanger-delay+ 6)

(defparameter %al.ext::+flanger-depth+ 4)

(defparameter %al.ext::+flanger-feedback+ 5)

(defparameter %al.ext::+flanger-max-delay+ 0.004000000189989805D0)

(defparameter %al.ext::+flanger-max-depth+ 1.0D0)

(defparameter %al.ext::+flanger-max-feedback+ 1.0D0)

(defparameter %al.ext::+flanger-max-phase+ 180)

(defparameter %al.ext::+flanger-max-rate+ 10.0D0)

(defparameter %al.ext::+flanger-max-waveform+ 1)

(defparameter %al.ext::+flanger-min-delay+ 0.0D0)

(defparameter %al.ext::+flanger-min-depth+ 0.0D0)

(defparameter %al.ext::+flanger-min-feedback+ -1.0D0)

(defparameter %al.ext::+flanger-min-phase+ -180)

(defparameter %al.ext::+flanger-min-rate+ 0.0D0)

(defparameter %al.ext::+flanger-min-waveform+ 0)

(defparameter %al.ext::+flanger-phase+ 2)

(defparameter %al.ext::+flanger-rate+ 3)

(defparameter %al.ext::+flanger-waveform+ 1)

(defparameter %al.ext::+flanger-waveform-sinusoid+ 0)

(defparameter %al.ext::+flanger-waveform-triangle+ 1)

(defparameter %al.ext::+float+ 5126)

(defparameter %al.ext::+foldback-event-block+ 16658)

(defparameter %al.ext::+foldback-event-start+ 16657)

(defparameter %al.ext::+foldback-event-stop+ 16659)

(defparameter %al.ext::+foldback-mode-mono+ 16641)

(defparameter %al.ext::+foldback-mode-stereo+ 16642)

(defparameter %al.ext::+format-51chn16+ 4619)

(defparameter %al.ext::+format-51chn32+ 4620)

(defparameter %al.ext::+format-51chn8+ 4618)

(defparameter %al.ext::+format-51chn-mulaw+ 65571)

(defparameter %al.ext::+format-61chn16+ 4622)

(defparameter %al.ext::+format-61chn32+ 4623)

(defparameter %al.ext::+format-61chn8+ 4621)

(defparameter %al.ext::+format-61chn-mulaw+ 65572)

(defparameter %al.ext::+format-71chn16+ 4625)

(defparameter %al.ext::+format-71chn32+ 4626)

(defparameter %al.ext::+format-71chn8+ 4624)

(defparameter %al.ext::+format-71chn-mulaw+ 65573)

(defparameter %al.ext::+format-bformat2d-16+ 131106)

(defparameter %al.ext::+format-bformat2d-8+ 131105)

(defparameter %al.ext::+format-bformat2d-float32+ 131107)

(defparameter %al.ext::+format-bformat2d-mulaw+ 65585)

(defparameter %al.ext::+format-bformat3d-16+ 131122)

(defparameter %al.ext::+format-bformat3d-8+ 131121)

(defparameter %al.ext::+format-bformat3d-float32+ 131123)

(defparameter %al.ext::+format-bformat3d-mulaw+ 65586)

(defparameter %al.ext::+format-ima-adpcm-mono16+ 65536)

(defparameter %al.ext::+format-ima-adpcm-stereo16+ 65537)

(defparameter %al.ext::+format-mono-alaw+ 65558)

(defparameter %al.ext::+format-mono-double+ 65554)

(defparameter %al.ext::+format-mono-float32+ 65552)

(defparameter %al.ext::+format-mono-ima4+ 4864)

(defparameter %al.ext::+format-mono-msadpcm+ 4866)

(defparameter %al.ext::+format-mono-mulaw+ 65556)

(defparameter %al.ext::+format-mono-mulaw+ 65556)

(defparameter %al.ext::+format-quad16+ 4613)

(defparameter %al.ext::+format-quad16-loki+ 65541)

(defparameter %al.ext::+format-quad32+ 4614)

(defparameter %al.ext::+format-quad8+ 4612)

(defparameter %al.ext::+format-quad8-loki+ 65540)

(defparameter %al.ext::+format-quad-mulaw+ 65569)

(defparameter %al.ext::+format-rear16+ 4616)

(defparameter %al.ext::+format-rear32+ 4617)

(defparameter %al.ext::+format-rear8+ 4615)

(defparameter %al.ext::+format-rear-mulaw+ 65570)

(defparameter %al.ext::+format-stereo-alaw+ 65559)

(defparameter %al.ext::+format-stereo-double+ 65555)

(defparameter %al.ext::+format-stereo-float32+ 65553)

(defparameter %al.ext::+format-stereo-ima4+ 4865)

(defparameter %al.ext::+format-stereo-msadpcm+ 4867)

(defparameter %al.ext::+format-stereo-mulaw+ 65557)

(defparameter %al.ext::+format-stereo-mulaw+ 65557)

(defparameter %al.ext::+format-vorbis+ 65539)

(defparameter %al.ext::+format-wave+ 65538)

(defparameter %al.ext::+frequency-shifter-default-frequency+ 0.0D0)

(defparameter %al.ext::+frequency-shifter-default-left-direction+ 0)

(defparameter %al.ext::+frequency-shifter-default-right-direction+ 0)

(defparameter %al.ext::+frequency-shifter-direction-down+ 0)

(defparameter %al.ext::+frequency-shifter-direction-off+ 2)

(defparameter %al.ext::+frequency-shifter-direction-up+ 1)

(defparameter %al.ext::+frequency-shifter-frequency+ 1)

(defparameter %al.ext::+frequency-shifter-left-direction+ 2)

(defparameter %al.ext::+frequency-shifter-max-frequency+ 24000.0D0)

(defparameter %al.ext::+frequency-shifter-max-left-direction+ 2)

(defparameter %al.ext::+frequency-shifter-max-right-direction+ 2)

(defparameter %al.ext::+frequency-shifter-min-frequency+ 0.0D0)

(defparameter %al.ext::+frequency-shifter-min-left-direction+ 0)

(defparameter %al.ext::+frequency-shifter-min-right-direction+ 0)

(defparameter %al.ext::+frequency-shifter-right-direction+ 3)

(defparameter %al.ext::+fuma+ 0)

(defparameter %al.ext::+gain-limit+ 8206)

(defparameter %al.ext::+highpass-default-gain+ 1.0D0)

(defparameter %al.ext::+highpass-default-gainlf+ 1.0D0)

(defparameter %al.ext::+highpass-gain+ 1)

(defparameter %al.ext::+highpass-gainlf+ 2)

(defparameter %al.ext::+highpass-max-gain+ 1.0D0)

(defparameter %al.ext::+highpass-max-gainlf+ 1.0D0)

(defparameter %al.ext::+highpass-min-gain+ 0.0D0)

(defparameter %al.ext::+highpass-min-gainlf+ 0.0D0)

(defparameter %al.ext::+internal-format+ 8200)

(defparameter %al.ext::+int+ 5124)

(defparameter %al.ext::+loki-ima-adpcm-format+ 1)

(defparameter %al.ext::+loki-wave-format+ 1)

(defparameter %al.ext::+loki-quadriphonic+ 1)

(defparameter %al.ext::+loop-points+ 8213)

(defparameter %al.ext::+lowpass-default-gain+ 1.0D0)

(defparameter %al.ext::+lowpass-default-gainhf+ 1.0D0)

(defparameter %al.ext::+lowpass-gain+ 1)

(defparameter %al.ext::+lowpass-gainhf+ 2)

(defparameter %al.ext::+lowpass-max-gain+ 1.0D0)

(defparameter %al.ext::+lowpass-max-gainhf+ 1.0D0)

(defparameter %al.ext::+lowpass-min-gain+ 0.0D0)

(defparameter %al.ext::+lowpass-min-gainhf+ 0.0D0)

(defparameter %al.ext::+max-air-absorption-factor+ 10.0D0)

(defparameter %al.ext::+max-auxiliary-send-filter-gainhf-auto+ 1)

(defparameter %al.ext::+max-auxiliary-send-filter-gain-auto+ 1)

(defparameter %al.ext::+max-cone-outer-gainhf+ 1.0D0)

(defparameter %al.ext::+max-direct-filter-gainhf-auto+ 1)

(defparameter %al.ext::+max-meters-per-unit+ 3.4028234663852886D+38)

(defparameter %al.ext::+max-room-rolloff-factor+ 10.0D0)

(defparameter %al.ext::+meters-per-unit+ 131076)

(defparameter %al.ext::+min-air-absorption-factor+ 0.0D0)

(defparameter %al.ext::+min-auxiliary-send-filter-gainhf-auto+ 0)

(defparameter %al.ext::+min-auxiliary-send-filter-gain-auto+ 0)

(defparameter %al.ext::+min-cone-outer-gainhf+ 0.0D0)

(defparameter %al.ext::+min-direct-filter-gainhf-auto+ 0)

(defparameter %al.ext::+min-meters-per-unit+ 1.1754943508222875D-38)

(defparameter %al.ext::+min-room-rolloff-factor+ 0.0D0)

(defparameter %al.ext::+mono16+ 4353)

(defparameter %al.ext::+mono32f+ 65552)

(defparameter %al.ext::+mono8+ 4352)

(defparameter %al.ext::+mono+ 5376)

(defparameter %al.ext::+n3d+ 2)

(defparameter %al.ext::+num-resamplers+ 4624)

(defparameter %al.ext::+pack-block-alignment+ 8205)

(defparameter %al.ext::+pitch-shifter-coarse-tune+ 1)

(defparameter %al.ext::+pitch-shifter-default-coarse-tune+ 12)

(defparameter %al.ext::+pitch-shifter-default-fine-tune+ 0)

(defparameter %al.ext::+pitch-shifter-fine-tune+ 2)

(defparameter %al.ext::+pitch-shifter-max-coarse-tune+ 12)

(defparameter %al.ext::+pitch-shifter-max-fine-tune+ 50)

(defparameter %al.ext::+pitch-shifter-min-coarse-tune+ -12)

(defparameter %al.ext::+pitch-shifter-min-fine-tune+ -50)

(defparameter %al.ext::+quad16+ 4613)

(defparameter %al.ext::+quad32f+ 4614)

(defparameter %al.ext::+quad8+ 4612)

(defparameter %al.ext::+quad+ 5379)

(defparameter %al.ext::+rear16+ 4616)

(defparameter %al.ext::+rear32f+ 4617)

(defparameter %al.ext::+rear8+ 4615)

(defparameter %al.ext::+rear+ 5378)

(defparameter %al.ext::+remix-unmatched+ 2)

(defparameter %al.ext::+resampler-name+ 4627)

(defparameter %al.ext::+reverb-air-absorption-gainhf+ 11)

(defparameter %al.ext::+reverb-decay-hflimit+ 13)

(defparameter %al.ext::+reverb-decay-hfratio+ 6)

(defparameter %al.ext::+reverb-decay-time+ 5)

(defparameter %al.ext::+reverb-default-air-absorption-gainhf+ 0.9940000176429749D0)

(defparameter %al.ext::+reverb-default-decay-hflimit+ 1)

(defparameter %al.ext::+reverb-default-decay-hfratio+ 0.8299999833106995D0)

(defparameter %al.ext::+reverb-default-decay-time+ 1.4900000095367432D0)

(defparameter %al.ext::+reverb-default-density+ 1.0D0)

(defparameter %al.ext::+reverb-default-diffusion+ 1.0D0)

(defparameter %al.ext::+reverb-default-gain+ 0.3199999928474426D0)

(defparameter %al.ext::+reverb-default-gainhf+ 0.8899999856948853D0)

(defparameter %al.ext::+reverb-default-late-reverb-delay+ 0.010999999940395355D0)

(defparameter %al.ext::+reverb-default-late-reverb-gain+ 1.2599999904632568D0)

(defparameter %al.ext::+reverb-default-reflections-delay+ 0.007000000216066837D0)

(defparameter %al.ext::+reverb-default-reflections-gain+ 0.05000000074505806D0)

(defparameter %al.ext::+reverb-default-room-rolloff-factor+ 0.0D0)

(defparameter %al.ext::+reverb-density+ 1)

(defparameter %al.ext::+reverb-diffusion+ 2)

(defparameter %al.ext::+reverb-gain+ 3)

(defparameter %al.ext::+reverb-gainhf+ 4)

(defparameter %al.ext::+reverb-late-reverb-delay+ 10)

(defparameter %al.ext::+reverb-late-reverb-gain+ 9)

(defparameter %al.ext::+reverb-max-air-absorption-gainhf+ 1.0D0)

(defparameter %al.ext::+reverb-max-decay-hflimit+ 1)

(defparameter %al.ext::+reverb-max-decay-hfratio+ 2.0D0)

(defparameter %al.ext::+reverb-max-decay-time+ 20.0D0)

(defparameter %al.ext::+reverb-max-density+ 1.0D0)

(defparameter %al.ext::+reverb-max-diffusion+ 1.0D0)

(defparameter %al.ext::+reverb-max-gain+ 1.0D0)

(defparameter %al.ext::+reverb-max-gainhf+ 1.0D0)

(defparameter %al.ext::+reverb-max-late-reverb-delay+ 0.10000000149011612D0)

(defparameter %al.ext::+reverb-max-late-reverb-gain+ 10.0D0)

(defparameter %al.ext::+reverb-max-reflections-delay+ 0.30000001192092896D0)

(defparameter %al.ext::+reverb-max-reflections-gain+ 3.1600000858306885D0)

(defparameter %al.ext::+reverb-max-room-rolloff-factor+ 10.0D0)

(defparameter %al.ext::+reverb-min-air-absorption-gainhf+ 0.8920000195503235D0)

(defparameter %al.ext::+reverb-min-decay-hflimit+ 0)

(defparameter %al.ext::+reverb-min-decay-hfratio+ 0.10000000149011612D0)

(defparameter %al.ext::+reverb-min-decay-time+ 0.10000000149011612D0)

(defparameter %al.ext::+reverb-min-density+ 0.0D0)

(defparameter %al.ext::+reverb-min-diffusion+ 0.0D0)

(defparameter %al.ext::+reverb-min-gain+ 0.0D0)

(defparameter %al.ext::+reverb-min-gainhf+ 0.0D0)

(defparameter %al.ext::+reverb-min-late-reverb-delay+ 0.0D0)

(defparameter %al.ext::+reverb-min-late-reverb-gain+ 0.0D0)

(defparameter %al.ext::+reverb-min-reflections-delay+ 0.0D0)

(defparameter %al.ext::+reverb-min-reflections-gain+ 0.0D0)

(defparameter %al.ext::+reverb-min-room-rolloff-factor+ 0.0D0)

(defparameter %al.ext::+reverb-reflections-delay+ 8)

(defparameter %al.ext::+reverb-reflections-gain+ 7)

(defparameter %al.ext::+reverb-room-rolloff-factor+ 12)

(defparameter %al.ext::+ring-modulator-default-frequency+ 440.0D0)

(defparameter %al.ext::+ring-modulator-default-highpass-cutoff+ 800.0D0)

(defparameter %al.ext::+ring-modulator-default-waveform+ 0)

(defparameter %al.ext::+ring-modulator-frequency+ 1)

(defparameter %al.ext::+ring-modulator-highpass-cutoff+ 2)

(defparameter %al.ext::+ring-modulator-max-frequency+ 8000.0D0)

(defparameter %al.ext::+ring-modulator-max-highpass-cutoff+ 24000.0D0)

(defparameter %al.ext::+ring-modulator-max-waveform+ 2)

(defparameter %al.ext::+ring-modulator-min-frequency+ 0.0D0)

(defparameter %al.ext::+ring-modulator-min-highpass-cutoff+ 0.0D0)

(defparameter %al.ext::+ring-modulator-min-waveform+ 0)

(defparameter %al.ext::+ring-modulator-sawtooth+ 1)

(defparameter %al.ext::+ring-modulator-sinusoid+ 0)

(defparameter %al.ext::+ring-modulator-square+ 2)

(defparameter %al.ext::+ring-modulator-waveform+ 3)

(defparameter %al.ext::+room-rolloff-factor+ 131080)

(defparameter %al.ext::+sample-length+ 8202)

(defparameter %al.ext::+sample-offset-clock+ 4610)

(defparameter %al.ext::+sample-offset-latency+ 4608)

(defparameter %al.ext::+sample-rw-offsets+ 4146)

(defparameter %al.ext::+sec-length+ 8203)

(defparameter %al.ext::+sec-offset-clock+ 4611)

(defparameter %al.ext::+sec-offset-latency+ 4609)

(defparameter %al.ext::+short+ 5122)

(defparameter %al.ext::+sn3d+ 1)

(defparameter %al.ext::+soft-msadpcm+ 1)

(defparameter %al.ext::+soft-bformat-ex+ 1)

(defparameter %al.ext::+soft-block-alignment+ 1)

(defparameter %al.ext::+soft-buffer-samples+ 1)

(defparameter %al.ext::+soft-buffer-sub-data+ 1)

(defparameter %al.ext::+soft-deferred-updates+ 1)

(defparameter %al.ext::+soft-direct-channels+ 1)

(defparameter %al.ext::+soft-direct-channels-remix+ 1)

(defparameter %al.ext::+soft-effect-target+ nil)

(defparameter %al.ext::+soft-events+ 1)

(defparameter %al.ext::+soft-gain-clamp-ex+ 1)

(defparameter %al.ext::+soft-loop-points+ 1)

(defparameter %al.ext::+soft-source-latency+ 1)

(defparameter %al.ext::+soft-source-length+ 1)

(defparameter %al.ext::+soft-source-resampler+ nil)

(defparameter %al.ext::+soft-source-spatialize+ nil)

(defparameter %al.ext::+source-distance-model+ 512)

(defparameter %al.ext::+source-radius+ 4145)

(defparameter %al.ext::+source-resampler+ 4626)

(defparameter %al.ext::+source-spatialize+ 4628)

(defparameter %al.ext::+stereo16+ 4355)

(defparameter %al.ext::+stereo32f+ 65553)

(defparameter %al.ext::+stereo8+ 4354)

(defparameter %al.ext::+stereo-angles+ 4144)

(defparameter %al.ext::+stereo+ 5377)

(defparameter %al.ext::+unpack-block-alignment+ 8204)

(defparameter %al.ext::+unsigned-byte3+ 5129)

(defparameter %al.ext::+unsigned-byte+ 5121)

(defparameter %al.ext::+unsigned-int+ 5125)

(defparameter %al.ext::+unsigned-short+ 5123)

(defparameter %al.ext::+vocal-morpher-default-phonemea+ 0)

(defparameter %al.ext::+vocal-morpher-default-phonemea-coarse-tuning+ 0)

(defparameter %al.ext::+vocal-morpher-default-phonemeb+ 10)

(defparameter %al.ext::+vocal-morpher-default-phonemeb-coarse-tuning+ 0)

(defparameter %al.ext::+vocal-morpher-default-rate+ 1.409999966621399D0)

(defparameter %al.ext::+vocal-morpher-default-waveform+ 0)

(defparameter %al.ext::+vocal-morpher-max-phonemea+ 29)

(defparameter %al.ext::+vocal-morpher-max-phonemea-coarse-tuning+ 24)

(defparameter %al.ext::+vocal-morpher-max-phonemeb+ 29)

(defparameter %al.ext::+vocal-morpher-max-phonemeb-coarse-tuning+ 24)

(defparameter %al.ext::+vocal-morpher-max-rate+ 10.0D0)

(defparameter %al.ext::+vocal-morpher-max-waveform+ 2)

(defparameter %al.ext::+vocal-morpher-min-phonemea+ 0)

(defparameter %al.ext::+vocal-morpher-min-phonemea-coarse-tuning+ -24)

(defparameter %al.ext::+vocal-morpher-min-phonemeb+ 0)

(defparameter %al.ext::+vocal-morpher-min-phonemeb-coarse-tuning+ -24)

(defparameter %al.ext::+vocal-morpher-min-rate+ 0.0D0)

(defparameter %al.ext::+vocal-morpher-min-waveform+ 0)

(defparameter %al.ext::+vocal-morpher-phonemea+ 1)

(defparameter %al.ext::+vocal-morpher-phonemea-coarse-tuning+ 2)

(defparameter %al.ext::+vocal-morpher-phonemeb+ 3)

(defparameter %al.ext::+vocal-morpher-phonemeb-coarse-tuning+ 4)

(defparameter %al.ext::+vocal-morpher-phoneme-a+ 0)

(defparameter %al.ext::+vocal-morpher-phoneme-aa+ 5)

(defparameter %al.ext::+vocal-morpher-phoneme-ae+ 6)

(defparameter %al.ext::+vocal-morpher-phoneme-ah+ 7)

(defparameter %al.ext::+vocal-morpher-phoneme-ao+ 8)

(defparameter %al.ext::+vocal-morpher-phoneme-b+ 15)

(defparameter %al.ext::+vocal-morpher-phoneme-d+ 16)

(defparameter %al.ext::+vocal-morpher-phoneme-e+ 1)

(defparameter %al.ext::+vocal-morpher-phoneme-eh+ 9)

(defparameter %al.ext::+vocal-morpher-phoneme-er+ 10)

(defparameter %al.ext::+vocal-morpher-phoneme-f+ 17)

(defparameter %al.ext::+vocal-morpher-phoneme-g+ 18)

(defparameter %al.ext::+vocal-morpher-phoneme-i+ 2)

(defparameter %al.ext::+vocal-morpher-phoneme-ih+ 11)

(defparameter %al.ext::+vocal-morpher-phoneme-iy+ 12)

(defparameter %al.ext::+vocal-morpher-phoneme-j+ 19)

(defparameter %al.ext::+vocal-morpher-phoneme-k+ 20)

(defparameter %al.ext::+vocal-morpher-phoneme-l+ 21)

(defparameter %al.ext::+vocal-morpher-phoneme-m+ 22)

(defparameter %al.ext::+vocal-morpher-phoneme-n+ 23)

(defparameter %al.ext::+vocal-morpher-phoneme-o+ 3)

(defparameter %al.ext::+vocal-morpher-phoneme-p+ 24)

(defparameter %al.ext::+vocal-morpher-phoneme-r+ 25)

(defparameter %al.ext::+vocal-morpher-phoneme-s+ 26)

(defparameter %al.ext::+vocal-morpher-phoneme-t+ 27)

(defparameter %al.ext::+vocal-morpher-phoneme-u+ 4)

(defparameter %al.ext::+vocal-morpher-phoneme-uh+ 13)

(defparameter %al.ext::+vocal-morpher-phoneme-uw+ 14)

(defparameter %al.ext::+vocal-morpher-phoneme-v+ 28)

(defparameter %al.ext::+vocal-morpher-phoneme-z+ 29)

(defparameter %al.ext::+vocal-morpher-rate+ 6)

(defparameter %al.ext::+vocal-morpher-waveform+ 5)

(defparameter %al.ext::+vocal-morpher-waveform-sawtooth+ 2)

(defparameter %al.ext::+vocal-morpher-waveform-sinusoid+ 0)

(defparameter %al.ext::+vocal-morpher-waveform-triangle+ 1)

(defparameter %al.ext::+eaxreverbproperties-defined+ nil)

(defparameter %al.ext::+presets-h+ nil)

(defparameter %al.ext::+reverb-preset-alley+ nil)

(defparameter %al.ext::+reverb-preset-arena+ nil)

(defparameter %al.ext::+reverb-preset-auditorium+ nil)

(defparameter %al.ext::+reverb-preset-bathroom+ nil)

(defparameter %al.ext::+reverb-preset-carpetedhallway+ nil)

(defparameter %al.ext::+reverb-preset-castle-alcove+ nil)

(defparameter %al.ext::+reverb-preset-castle-courtyard+ nil)

(defparameter %al.ext::+reverb-preset-castle-cupboard+ nil)

(defparameter %al.ext::+reverb-preset-castle-hall+ nil)

(defparameter %al.ext::+reverb-preset-castle-largeroom+ nil)

(defparameter %al.ext::+reverb-preset-castle-longpassage+ nil)

(defparameter %al.ext::+reverb-preset-castle-mediumroom+ nil)

(defparameter %al.ext::+reverb-preset-castle-shortpassage+ nil)

(defparameter %al.ext::+reverb-preset-castle-smallroom+ nil)

(defparameter %al.ext::+reverb-preset-cave+ nil)

(defparameter %al.ext::+reverb-preset-chapel+ nil)

(defparameter %al.ext::+reverb-preset-city+ nil)

(defparameter %al.ext::+reverb-preset-city-abandoned+ nil)

(defparameter %al.ext::+reverb-preset-city-library+ nil)

(defparameter %al.ext::+reverb-preset-city-museum+ nil)

(defparameter %al.ext::+reverb-preset-city-streets+ nil)

(defparameter %al.ext::+reverb-preset-city-subway+ nil)

(defparameter %al.ext::+reverb-preset-city-underpass+ nil)

(defparameter %al.ext::+reverb-preset-concerthall+ nil)

(defparameter %al.ext::+reverb-preset-dizzy+ nil)

(defparameter %al.ext::+reverb-preset-dome-saintpauls+ nil)

(defparameter %al.ext::+reverb-preset-dome-tomb+ nil)

(defparameter %al.ext::+reverb-preset-driving-commentator+ nil)

(defparameter %al.ext::+reverb-preset-driving-emptygrandstand+ nil)

(defparameter %al.ext::+reverb-preset-driving-fullgrandstand+ nil)

(defparameter %al.ext::+reverb-preset-driving-incar-luxury+ nil)

(defparameter %al.ext::+reverb-preset-driving-incar-racer+ nil)

(defparameter %al.ext::+reverb-preset-driving-incar-sports+ nil)

(defparameter %al.ext::+reverb-preset-driving-pitgarage+ nil)

(defparameter %al.ext::+reverb-preset-driving-tunnel+ nil)

(defparameter %al.ext::+reverb-preset-drugged+ nil)

(defparameter %al.ext::+reverb-preset-dustyroom+ nil)

(defparameter %al.ext::+reverb-preset-factory-alcove+ nil)

(defparameter %al.ext::+reverb-preset-factory-courtyard+ nil)

(defparameter %al.ext::+reverb-preset-factory-cupboard+ nil)

(defparameter %al.ext::+reverb-preset-factory-hall+ nil)

(defparameter %al.ext::+reverb-preset-factory-largeroom+ nil)

(defparameter %al.ext::+reverb-preset-factory-longpassage+ nil)

(defparameter %al.ext::+reverb-preset-factory-mediumroom+ nil)

(defparameter %al.ext::+reverb-preset-factory-shortpassage+ nil)

(defparameter %al.ext::+reverb-preset-factory-smallroom+ nil)

(defparameter %al.ext::+reverb-preset-forest+ nil)

(defparameter %al.ext::+reverb-preset-generic+ nil)

(defparameter %al.ext::+reverb-preset-hallway+ nil)

(defparameter %al.ext::+reverb-preset-hangar+ nil)

(defparameter %al.ext::+reverb-preset-icepalace-alcove+ nil)

(defparameter %al.ext::+reverb-preset-icepalace-courtyard+ nil)

(defparameter %al.ext::+reverb-preset-icepalace-cupboard+ nil)

(defparameter %al.ext::+reverb-preset-icepalace-hall+ nil)

(defparameter %al.ext::+reverb-preset-icepalace-largeroom+ nil)

(defparameter %al.ext::+reverb-preset-icepalace-longpassage+ nil)

(defparameter %al.ext::+reverb-preset-icepalace-mediumroom+ nil)

(defparameter %al.ext::+reverb-preset-icepalace-shortpassage+ nil)

(defparameter %al.ext::+reverb-preset-icepalace-smallroom+ nil)

(defparameter %al.ext::+reverb-preset-livingroom+ nil)

(defparameter %al.ext::+reverb-preset-mood-heaven+ nil)

(defparameter %al.ext::+reverb-preset-mood-hell+ nil)

(defparameter %al.ext::+reverb-preset-mood-memory+ nil)

(defparameter %al.ext::+reverb-preset-mountains+ nil)

(defparameter %al.ext::+reverb-preset-outdoors-backyard+ nil)

(defparameter %al.ext::+reverb-preset-outdoors-creek+ nil)

(defparameter %al.ext::+reverb-preset-outdoors-deepcanyon+ nil)

(defparameter %al.ext::+reverb-preset-outdoors-rollingplains+ nil)

(defparameter %al.ext::+reverb-preset-outdoors-valley+ nil)

(defparameter %al.ext::+reverb-preset-paddedcell+ nil)

(defparameter %al.ext::+reverb-preset-parkinglot+ nil)

(defparameter %al.ext::+reverb-preset-pipe-large+ nil)

(defparameter %al.ext::+reverb-preset-pipe-longthin+ nil)

(defparameter %al.ext::+reverb-preset-pipe-resonant+ nil)

(defparameter %al.ext::+reverb-preset-pipe-small+ nil)

(defparameter %al.ext::+reverb-preset-plain+ nil)

(defparameter %al.ext::+reverb-preset-prefab-caravan+ nil)

(defparameter %al.ext::+reverb-preset-prefab-outhouse+ nil)

(defparameter %al.ext::+reverb-preset-prefab-practiseroom+ nil)

(defparameter %al.ext::+reverb-preset-prefab-schoolroom+ nil)

(defparameter %al.ext::+reverb-preset-prefab-workshop+ nil)

(defparameter %al.ext::+reverb-preset-psychotic+ nil)

(defparameter %al.ext::+reverb-preset-quarry+ nil)

(defparameter %al.ext::+reverb-preset-room+ nil)

(defparameter %al.ext::+reverb-preset-sewerpipe+ nil)

(defparameter %al.ext::+reverb-preset-smallwaterroom+ nil)

(defparameter %al.ext::+reverb-preset-spacestation-alcove+ nil)

(defparameter %al.ext::+reverb-preset-spacestation-cupboard+ nil)

(defparameter %al.ext::+reverb-preset-spacestation-hall+ nil)

(defparameter %al.ext::+reverb-preset-spacestation-largeroom+ nil)

(defparameter %al.ext::+reverb-preset-spacestation-longpassage+ nil)

(defparameter %al.ext::+reverb-preset-spacestation-mediumroom+ nil)

(defparameter %al.ext::+reverb-preset-spacestation-shortpassage+ nil)

(defparameter %al.ext::+reverb-preset-spacestation-smallroom+ nil)

(defparameter %al.ext::+reverb-preset-sport-emptystadium+ nil)

(defparameter %al.ext::+reverb-preset-sport-fullstadium+ nil)

(defparameter %al.ext::+reverb-preset-sport-gymnasium+ nil)

(defparameter %al.ext::+reverb-preset-sport-largeswimmingpool+ nil)

(defparameter %al.ext::+reverb-preset-sport-smallswimmingpool+ nil)

(defparameter %al.ext::+reverb-preset-sport-squashcourt+ nil)

(defparameter %al.ext::+reverb-preset-sport-stadiumtannoy+ nil)

(defparameter %al.ext::+reverb-preset-stonecorridor+ nil)

(defparameter %al.ext::+reverb-preset-stoneroom+ nil)

(defparameter %al.ext::+reverb-preset-underwater+ nil)

(defparameter %al.ext::+reverb-preset-wooden-alcove+ nil)

(defparameter %al.ext::+reverb-preset-wooden-courtyard+ nil)

(defparameter %al.ext::+reverb-preset-wooden-cupboard+ nil)

(defparameter %al.ext::+reverb-preset-wooden-hall+ nil)

(defparameter %al.ext::+reverb-preset-wooden-largeroom+ nil)

(defparameter %al.ext::+reverb-preset-wooden-longpassage+ nil)

(defparameter %al.ext::+reverb-preset-wooden-mediumroom+ nil)

(defparameter %al.ext::+reverb-preset-wooden-shortpassage+ nil)

(defparameter %al.ext::+reverb-preset-wooden-smallroom+ nil)

(declaim (inline %al.ext::defer-updates))

(cffi:defcfun ("alDeferUpdatesSOFT" %al.ext::defer-updates) :void)

(cffi:defctype %al.ext::eventproc (claw-utils:claw-pointer :void))

(declaim (inline %al.ext::event-callback))

(cffi:defcfun ("alEventCallbackSOFT" %al.ext::event-callback)
              :void
              (%al.ext::callback %al.ext::eventproc)
              (%al.ext::user-param (claw-utils:claw-pointer :void)))

(declaim (inline %al.ext::process-updates))

(cffi:defcfun ("alProcessUpdatesSOFT" %al.ext::process-updates) :void)

(declaim (inline %al.ext::request-foldback-stop))

(cffi:defcfun ("alRequestFoldbackStop"
               %al.ext::request-foldback-stop)
              :void)

(cffi:defcstruct (%al.ext::|C:@SA@EFXEAXREVERBPROPERTIES| :size 108)
                 (%al.ext::fl-density :float :offset 0)
                 (%al.ext::fl-diffusion :float :offset 4)
                 (%al.ext::fl-gain :float :offset 8)
                 (%al.ext::fl-gain-hf :float :offset 12)
                 (%al.ext::fl-gain-lf :float :offset 16)
                 (%al.ext::fl-decay-time :float :offset 20)
                 (%al.ext::fl-decay-hf-ratio :float :offset 24)
                 (%al.ext::fl-decay-lf-ratio :float :offset 28)
                 (%al.ext::fl-reflections-gain :float :offset 32)
                 (%al.ext::fl-reflections-delay :float :offset 36)
                 (%al.ext::fl-reflections-pan :float :count 3 :offset
                  40)
                 (%al.ext::fl-late-reverb-gain :float :offset 52)
                 (%al.ext::fl-late-reverb-delay :float :offset 56)
                 (%al.ext::fl-late-reverb-pan :float :count 3 :offset
                  60)
                 (%al.ext::fl-echo-time :float :offset 72)
                 (%al.ext::fl-echo-depth :float :offset 76)
                 (%al.ext::fl-modulation-time :float :offset 80)
                 (%al.ext::fl-modulation-depth :float :offset 84)
                 (%al.ext::fl-air-absorption-gain-hf :float :offset
                  88)
                 (%al.ext::fl-hf-reference :float :offset 92)
                 (%al.ext::fl-lf-reference :float :offset 96)
                 (%al.ext::fl-room-rolloff-factor :float :offset 100)
                 (%al.ext::i-decay-hf-limit :int :offset 104))

(cffi:defctype %al.ext::eaxreverbproperties
               (:struct %al.ext::|C:@SA@EFXEAXREVERBPROPERTIES|))

(cffi:defctype %al.ext::int64 :long)

(cffi:defctype %al.ext::uint64 :unsigned-long)

(cffi:defctype %al.ext::int64 :long)

(cffi:defctype %al.ext::uint64 :unsigned-long)

(eval-when (:load-toplevel :compile-toplevel :execute)
  (export '%al.ext::+device-latency+ :%al.ext)
  (export '%al.ext::+default-auxiliary-send-filter-gain-auto+
          :%al.ext)
  (export '%al.ext::+eaxreverb-min-hfreference+ :%al.ext)
  (export '%al.ext::+chorus-waveform-sinusoid+ :%al.ext)
  (export '%al.ext::+reverb-preset-castle-shortpassage+ :%al.ext)
  (export '%al.ext::+format-bformat2d-8+ :%al.ext)
  (export '%al.ext::+flanger-min-waveform+ :%al.ext)
  (export '%al.ext::+frequency-shifter-min-left-direction+ :%al.ext)
  (export '%al.ext::+eaxreverb-decay-hflimit+ :%al.ext)
  (export '%al.ext::+5point1-8+ :%al.ext)
  (export '%al.ext::+effect-dedicated-dialogue+ :%al.ext)
  (export '%al.ext::+hrtf-status+ :%al.ext)
  (export '%al.ext::+flanger-default-waveform+ :%al.ext)
  (export '%al.ext::+ring-modulator-default-highpass-cutoff+
          :%al.ext)
  (export '%al.ext::+equalizer-min-low-cutoff+ :%al.ext)
  (export '%al.ext::+reverb-gainhf+ :%al.ext)
  (export '%al.ext::+reverb-default-gainhf+ :%al.ext)
  (export '%al.ext::+reverb-preset-outdoors-backyard+ :%al.ext)
  (export '%al.ext::+max-room-rolloff-factor+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-lfreference+ :%al.ext)
  (export '%al.ext::+reverb-preset-livingroom+ :%al.ext)
  (export '%al.ext::request-foldback-stop :%al.ext)
  (export '%al.ext::+rear+ :%al.ext)
  (export '%al.ext::fl-decay-hf-ratio :%al.ext)
  (export '%al.ext::+source-spatialize+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-decay-time+ :%al.ext)
  (export '%al.ext::+reverb-preset-driving-pitgarage+ :%al.ext)
  (export '%al.ext::+format-61chn16+ :%al.ext)
  (export '%al.ext::+reverb-preset-pipe-small+ :%al.ext)
  (export '%al.ext::+reverb-preset-generic+ :%al.ext)
  (export '%al.ext::+highpass-min-gain+ :%al.ext)
  (export '%al.ext::+format-71chn8+ :%al.ext)
  (export '%al.ext::+ring-modulator-waveform+ :%al.ext)
  (export '%al.ext::+distortion-max-eqcenter+ :%al.ext)
  (export '%al.ext::+resampler-name+ :%al.ext)
  (export '%al.ext::+lowpass-gain+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-lfreference+ :%al.ext)
  (export '%al.ext::+equalizer-min-mid2-center+ :%al.ext)
  (export '%al.ext::+ext-default-filter-order+ :%al.ext)
  (export '%al.ext::+reverb-preset-sport-fullstadium+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-o+ :%al.ext)
  (export '%al.ext::+echo-default-delay+ :%al.ext)
  (export '%al.ext::+format-bformat3d-mulaw+ :%al.ext)
  (export '%al.ext::+ring-modulator-min-waveform+ :%al.ext)
  (export '%al.ext::+format-71chn16+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-z+ :%al.ext)
  (export '%al.ext::+autowah-min-release-time+ :%al.ext)
  (export '%al.ext::+reverb-reflections-delay+ :%al.ext)
  (export '%al.ext::+echo-default-feedback+ :%al.ext)
  (export '%al.ext::+reverb-preset-psychotic+ :%al.ext)
  (export '%al.ext::+reverb-min-late-reverb-gain+ :%al.ext)
  (export '%al.ext::+equalizer-max-high-gain+ :%al.ext)
  (export '%al.ext::+echo-max-spread+ :%al.ext)
  (export '%al.ext::+reverb-preset-wooden-shortpassage+ :%al.ext)
  (export '%al.ext::+rear16+ :%al.ext)
  (export '%al.ext::+reverb-min-decay-hflimit+ :%al.ext)
  (export '%al.ext::+reverb-max-late-reverb-delay+ :%al.ext)
  (export '%al.ext::+echo-max-delay+ :%al.ext)
  (export '%al.ext::+mono16+ :%al.ext)
  (export '%al.ext::+sample-offset-latency+ :%al.ext)
  (export '%al.ext::defer-updates :%al.ext)
  (export '%al.ext::+flanger-default-rate+ :%al.ext)
  (export '%al.ext::+reverb-preset-mountains+ :%al.ext)
  (export '%al.ext::+format-rear8+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phonemeb+ :%al.ext)
  (export '%al.ext::+event-type-buffer-completed+ :%al.ext)
  (export '%al.ext::+reverb-max-room-rolloff-factor+ :%al.ext)
  (export '%al.ext::+equalizer-default-mid2-gain+ :%al.ext)
  (export '%al.ext::+eaxreverb-late-reverb-pan+ :%al.ext)
  (export '%al.ext::fl-gain :%al.ext)
  (export '%al.ext::+format-mono-double+ :%al.ext)
  (export '%al.ext::+distortion-min-gain+ :%al.ext)
  (export '%al.ext::+echo-max-lrdelay+ :%al.ext)
  (export '%al.ext::+reverb-preset-mood-heaven+ :%al.ext)
  (export '%al.ext::+lowpass-max-gainhf+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-decay-lfratio+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-gain+ :%al.ext)
  (export '%al.ext::+filter-lowpass+ :%al.ext)
  (export '%al.ext::+equalizer-min-mid1-gain+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-decay-hfratio+ :%al.ext)
  (export '%al.ext::process-updates :%al.ext)
  (export '%al.ext::+reverb-min-air-absorption-gainhf+ :%al.ext)
  (export '%al.ext::+autowah-release-time+ :%al.ext)
  (export '%al.ext::+default-auxiliary-send-filter-gainhf-auto+
          :%al.ext)
  (export '%al.ext::+chan-cd-loki+ :%al.ext)
  (export '%al.ext::+reverb-preset-city-streets+ :%al.ext)
  (export '%al.ext::+ring-modulator-max-waveform+ :%al.ext)
  (export '%al.ext::+chorus-min-delay+ :%al.ext)
  (export '%al.ext::+eaxreverb-air-absorption-gainhf+ :%al.ext)
  (export '%al.ext::+pack-block-alignment+ :%al.ext)
  (export '%al.ext::+bandpass-min-gainhf+ :%al.ext)
  (export '%al.ext::+eaxreverb-modulation-depth+ :%al.ext)
  (export '%al.ext::+flanger-default-feedback+ :%al.ext)
  (export '%al.ext::+soft-deferred-updates+ :%al.ext)
  (export '%al.ext::+ext-source-radius+ :%al.ext)
  (export '%al.ext::+hrtf-enabled+ :%al.ext)
  (export '%al.ext::+reverb-preset-room+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-modulation-time+ :%al.ext)
  (export '%al.ext::+reverb-preset-mood-memory+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-uh+ :%al.ext)
  (export '%al.ext::+effect-echo+ :%al.ext)
  (export '%al.ext::+default-room-rolloff-factor+ :%al.ext)
  (export '%al.ext::+distortion-max-eqbandwidth+ :%al.ext)
  (export '%al.ext::+format-quad16-loki+ :%al.ext)
  (export '%al.ext::+reverb-preset-wooden-alcove+ :%al.ext)
  (export '%al.ext::+format-mono-alaw+ :%al.ext)
  (export '%al.ext::+reverb-preset-castle-mediumroom+ :%al.ext)
  (export '%al.ext::+sample-rw-offsets+ :%al.ext)
  (export '%al.ext::+reverb-preset-concerthall+ :%al.ext)
  (export '%al.ext::+ext-mcformats+ :%al.ext)
  (export '%al.ext::+sec-offset-latency+ :%al.ext)
  (export '%al.ext::+event-type-source-state-changed+ :%al.ext)
  (export '%al.ext::+lowpass-min-gainhf+ :%al.ext)
  (export '%al.ext::+effect-ring-modulator+ :%al.ext)
  (export '%al.ext::+soft-source-spatialize+ :%al.ext)
  (export '%al.ext::+bandpass-gainhf+ :%al.ext)
  (export '%al.ext::+reverb-air-absorption-gainhf+ :%al.ext)
  (export '%al.ext::fl-hf-reference :%al.ext)
  (export '%al.ext::+format-71chn-mulaw+ :%al.ext)
  (export '%al.ext::+ext-float32+ :%al.ext)
  (export '%al.ext::+format-mono-float32+ :%al.ext)
  (export '%al.ext::+format-quad8+ :%al.ext)
  (export '%al.ext::+effect-equalizer+ :%al.ext)
  (export '%al.ext::+auxiliary-send-filter-gain-auto+ :%al.ext)
  (export '%al.ext::+ext-thread-local-context+ :%al.ext)
  (export '%al.ext::+eaxreverb-room-rolloff-factor+ :%al.ext)
  (export '%al.ext::+effect-compressor+ :%al.ext)
  (export '%al.ext::+ext-source-distance-model+ :%al.ext)
  (export '%al.ext::+unsigned-byte3+ :%al.ext)
  (export '%al.ext::+effect-vocal-morpher+ :%al.ext)
  (export '%al.ext::fl-reflections-gain :%al.ext)
  (export '%al.ext::+vocal-morpher-max-phonemea+ :%al.ext)
  (export '%al.ext::+bandpass-min-gain+ :%al.ext)
  (export '%al.ext::+num-resamplers+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-room-rolloff-factor+ :%al.ext)
  (export '%al.ext::+max-cone-outer-gainhf+ :%al.ext)
  (export '%al.ext::+hrtf-specifier+ :%al.ext)
  (export '%al.ext::+ext-foldback+ :%al.ext)
  (export '%al.ext::+effect-pitch-shifter+ :%al.ext)
  (export '%al.ext::+ext-stereo-angles+ :%al.ext)
  (export '%al.ext::+dont-care+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-a+ :%al.ext)
  (export '%al.ext::+reverb-preset-prefab-caravan+ :%al.ext)
  (export '%al.ext::fl-decay-lf-ratio :%al.ext)
  (export '%al.ext::+format-bformat3d-float32+ :%al.ext)
  (export '%al.ext::+max-auxiliary-sends+ :%al.ext)
  (export '%al.ext::fl-density :%al.ext)
  (export '%al.ext::+unsigned-short+ :%al.ext)
  (export '%al.ext::+reverb-preset-driving-incar-luxury+ :%al.ext)
  (export '%al.ext::fl-gain-hf :%al.ext)
  (export '%al.ext::+ext-ima4+ :%al.ext)
  (export '%al.ext::+reverb-max-gain+ :%al.ext)
  (export '%al.ext::+reverb-default-late-reverb-gain+ :%al.ext)
  (export '%al.ext::+soft-loop-points+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-k+ :%al.ext)
  (export '%al.ext::fl-air-absorption-gain-hf :%al.ext)
  (export '%al.ext::+reverb-preset-sport-gymnasium+ :%al.ext)
  (export '%al.ext::+reverb-preset-city-abandoned+ :%al.ext)
  (export '%al.ext::+flanger-feedback+ :%al.ext)
  (export '%al.ext::+flanger-min-feedback+ :%al.ext)
  (export '%al.ext::+num-hrtf-specifiers+ :%al.ext)
  (export '%al.ext::+min-cone-outer-gainhf+ :%al.ext)
  (export '%al.ext::+hrtf+ :%al.ext)
  (export '%al.ext::+equalizer-default-mid2-width+ :%al.ext)
  (export '%al.ext::+format-vorbis+ :%al.ext)
  (export '%al.ext::+reverb-preset-sport-largeswimmingpool+ :%al.ext)
  (export '%al.ext::+air-absorption-factor+ :%al.ext)
  (export '%al.ext::+reverb-preset-factory-courtyard+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-late-reverb-pan-xyz+ :%al.ext)
  (export '%al.ext::+chorus-min-waveform+ :%al.ext)
  (export '%al.ext::+reverb-min-gain+ :%al.ext)
  (export '%al.ext::fl-decay-time :%al.ext)
  (export '%al.ext::+reverb-preset-icepalace-shortpassage+ :%al.ext)
  (export '%al.ext::+soft-direct-channels+ :%al.ext)
  (export '%al.ext::+reverb-preset-stoneroom+ :%al.ext)
  (export '%al.ext::+reverb-gain+ :%al.ext)
  (export '%al.ext::+equalizer-mid1-width+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phonemeb-coarse-tuning+ :%al.ext)
  (export '%al.ext::+equalizer-low-gain+ :%al.ext)
  (export '%al.ext::+equalizer-default-low-cutoff+ :%al.ext)
  (export '%al.ext::+reverb-preset-dustyroom+ :%al.ext)
  (export '%al.ext::+default-air-absorption-factor+ :%al.ext)
  (export '%al.ext::+output-limiter+ :%al.ext)
  (export '%al.ext::+reverb-max-reflections-delay+ :%al.ext)
  (export '%al.ext::+highpass-gainlf+ :%al.ext)
  (export '%al.ext::+chorus-default-delay+ :%al.ext)
  (export '%al.ext::fl-late-reverb-gain :%al.ext)
  (export '%al.ext::+filter-first-parameter+ :%al.ext)
  (export '%al.ext::+reverb-preset-underwater+ :%al.ext)
  (export '%al.ext::+ext-static-buffer+ :%al.ext)
  (export '%al.ext::+ambisonic-layout+ :%al.ext)
  (export '%al.ext::+foldback-mode-stereo+ :%al.ext)
  (export '%al.ext::+reverb-max-gainhf+ :%al.ext)
  (export '%al.ext::+bandpass-max-gain+ :%al.ext)
  (export '%al.ext::+frequency-shifter-right-direction+ :%al.ext)
  (export '%al.ext::+eaxreverb-late-reverb-gain+ :%al.ext)
  (export '%al.ext::+compressor-onoff+ :%al.ext)
  (export '%al.ext::+echo-default-spread+ :%al.ext)
  (export '%al.ext::+7point1+ :%al.ext)
  (export '%al.ext::+loop-points+ :%al.ext)
  (export '%al.ext::+reverb-preset-city-library+ :%al.ext)
  (export '%al.ext::+format-bformat2d-16+ :%al.ext)
  (export '%al.ext::+double+ :%al.ext)
  (export '%al.ext::+quad32f+ :%al.ext)
  (export '%al.ext::+compressor-max-onoff+ :%al.ext)
  (export '%al.ext::+max-ambisonic-order+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-gainhf+ :%al.ext)
  (export '%al.ext::+eaxreverb-decay-hfratio+ :%al.ext)
  (export '%al.ext::+reverb-preset-plain+ :%al.ext)
  (export '%al.ext::+format-bformat3d-16+ :%al.ext)
  (export '%al.ext::+source-resampler+ :%al.ext)
  (export '%al.ext::+equalizer-mid2-center+ :%al.ext)
  (export '%al.ext::+ring-modulator-square+ :%al.ext)
  (export '%al.ext::+hrtf-headphones-detected+ :%al.ext)
  (export '%al.ext::fl-modulation-depth :%al.ext)
  (export '%al.ext::+distortion-max-gain+ :%al.ext)
  (export '%al.ext::+autowah-min-resonance+ :%al.ext)
  (export '%al.ext::+reverb-diffusion+ :%al.ext)
  (export '%al.ext::+equalizer-max-mid2-gain+ :%al.ext)
  (export '%al.ext::+source-distance-model+ :%al.ext)
  (export '%al.ext::+default-resampler+ :%al.ext)
  (export '%al.ext::+equalizer-min-high-gain+ :%al.ext)
  (export '%al.ext::+equalizer-max-low-gain+ :%al.ext)
  (export '%al.ext::+ext-mulaw+ :%al.ext)
  (export '%al.ext::+reverb-preset-dome-tomb+ :%al.ext)
  (export '%al.ext::+reverb-min-density+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-t+ :%al.ext)
  (export '%al.ext::+rear8+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-i+ :%al.ext)
  (export '%al.ext::+deferred-updates+ :%al.ext)
  (export '%al.ext::+drop-unmatched+ :%al.ext)
  (export '%al.ext::+chorus-waveform+ :%al.ext)
  (export '%al.ext::+reverb-preset-sewerpipe+ :%al.ext)
  (export '%al.ext::+echo-max-damping+ :%al.ext)
  (export '%al.ext::+soft-events+ :%al.ext)
  (export '%al.ext::+format-51chn8+ :%al.ext)
  (export '%al.ext::+reverb-preset-castle-cupboard+ :%al.ext)
  (export '%al.ext::+highpass-default-gainlf+ :%al.ext)
  (export '%al.ext::+autowah-default-attack-time+ :%al.ext)
  (export '%al.ext::+reverb-default-density+ :%al.ext)
  (export '%al.ext::+eaxreverb-echo-time+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-late-reverb-delay+ :%al.ext)
  (export '%al.ext::+equalizer-min-high-cutoff+ :%al.ext)
  (export '%al.ext::+sn3d+ :%al.ext)
  (export '%al.ext::+format-ima-adpcm-stereo16+ :%al.ext)
  (export '%al.ext::+distortion-min-eqbandwidth+ :%al.ext)
  (export '%al.ext::+soft-loopback-bformat+ :%al.ext)
  (export '%al.ext::+vocal-morpher-max-phonemea-coarse-tuning+
          :%al.ext)
  (export '%al.ext::+eaxreverb-decay-time+ :%al.ext)
  (export '%al.ext::+format-rear16+ :%al.ext)
  (export '%al.ext::+echo-min-lrdelay+ :%al.ext)
  (export '%al.ext::+soft-source-length+ :%al.ext)
  (export '%al.ext::+pitch-shifter-fine-tune+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-air-absorption-gainhf+ :%al.ext)
  (export '%al.ext::+reverb-preset-outdoors-rollingplains+ :%al.ext)
  (export '%al.ext::+vocal-morpher-max-waveform+ :%al.ext)
  (export '%al.ext::+distortion-lowpass-cutoff+ :%al.ext)
  (export '%al.ext::+ext-alaw+ :%al.ext)
  (export '%al.ext::+direct-filter-gainhf-auto+ :%al.ext)
  (export '%al.ext::+5point1+ :%al.ext)
  (export '%al.ext::+reverb-default-diffusion+ :%al.ext)
  (export '%al.ext::+reverb-preset-parkinglot+ :%al.ext)
  (export '%al.ext::+equalizer-default-mid1-width+ :%al.ext)
  (export '%al.ext::+reverb-preset-castle-smallroom+ :%al.ext)
  (export '%al.ext::+vocal-morpher-waveform-sawtooth+ :%al.ext)
  (export '%al.ext::+format-quad32+ :%al.ext)
  (export '%al.ext::+reverb-preset-pipe-resonant+ :%al.ext)
  (export '%al.ext::+vocal-morpher-min-waveform+ :%al.ext)
  (export '%al.ext::+byte+ :%al.ext)
  (export '%al.ext::+reverb-preset-sport-squashcourt+ :%al.ext)
  (export '%al.ext::+format-51chn16+ :%al.ext)
  (export '%al.ext::+7point1-8+ :%al.ext)
  (export '%al.ext::+foldback-event-block+ :%al.ext)
  (export '%al.ext::+reverb-default-room-rolloff-factor+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-f+ :%al.ext)
  (export '%al.ext::+effectslot-target+ :%al.ext)
  (export '%al.ext::+equalizer-min-mid1-center+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-uw+ :%al.ext)
  (export '%al.ext::+vocal-morpher-default-rate+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-echo-depth+ :%al.ext)
  (export '%al.ext::+highpass-max-gainlf+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-echo-time+ :%al.ext)
  (export '%al.ext::+distortion-eqcenter+ :%al.ext)
  (export '%al.ext::+eaxreverb-reflections-pan+ :%al.ext)
  (export '%al.ext::+echo-min-damping+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phonemea+ :%al.ext)
  (export '%al.ext::+vocal-morpher-min-phonemea+ :%al.ext)
  (export '%al.ext::+frequency-shifter-direction-up+ :%al.ext)
  (export '%al.ext::+flanger-default-phase+ :%al.ext)
  (export '%al.ext::+lowpass-default-gainhf+ :%al.ext)
  (export '%al.ext::+min-meters-per-unit+ :%al.ext)
  (export '%al.ext::+chorus-feedback+ :%al.ext)
  (export '%al.ext::+format-quad8-loki+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-p+ :%al.ext)
  (export '%al.ext::+max-auxiliary-send-filter-gain-auto+ :%al.ext)
  (export '%al.ext::+reverb-preset-driving-emptygrandstand+ :%al.ext)
  (export '%al.ext::+effect-distortion+ :%al.ext)
  (export '%al.ext::+ext-prototypes+ :%al.ext)
  (export '%al.ext::+rear32f+ :%al.ext)
  (export '%al.ext::+reverb-late-reverb-gain+ :%al.ext)
  (export '%al.ext::+loki-quadriphonic+ :%al.ext)
  (export '%al.ext::+reverb-preset-city+ :%al.ext)
  (export '%al.ext::+effectslot-effect+ :%al.ext)
  (export '%al.ext::+reverb-preset-prefab-outhouse+ :%al.ext)
  (export '%al.ext::+format-mono-mulaw+ :%al.ext)
  (export '%al.ext::+echo-min-spread+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-aa+ :%al.ext)
  (export '%al.ext::+format-stereo-float32+ :%al.ext)
  (export '%al.ext::+reverb-preset-smallwaterroom+ :%al.ext)
  (export '%al.ext::+format-ima-adpcm-mono16+ :%al.ext)
  (export '%al.ext::+chorus-min-depth+ :%al.ext)
  (export '%al.ext::+reverb-preset-factory-alcove+ :%al.ext)
  (export '%al.ext::+vocal-morpher-default-phonemeb-coarse-tuning+
          :%al.ext)
  (export '%al.ext::+reverb-preset-wooden-hall+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-e+ :%al.ext)
  (export '%al.ext::+frequency-shifter-left-direction+ :%al.ext)
  (export '%al.ext::+soft-source-resampler+ :%al.ext)
  (export '%al.ext::+chorus-min-phase+ :%al.ext)
  (export '%al.ext::+%h+ :%al.ext)
  (export '%al.ext::+reverb-preset-stonecorridor+ :%al.ext)
  (export '%al.ext::+echo-spread+ :%al.ext)
  (export '%al.ext::+chorus-max-delay+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-late-reverb-delay+ :%al.ext)
  (export '%al.ext::+direct-filter+ :%al.ext)
  (export '%al.ext::+soft-device-clock+ :%al.ext)
  (export '%al.ext::+effect-null+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-reflections-delay+ :%al.ext)
  (export '%al.ext::+vocal-morpher-waveform-sinusoid+ :%al.ext)
  (export '%al.ext::+equalizer-max-low-cutoff+ :%al.ext)
  (export '%al.ext::+reverb-preset-driving-tunnel+ :%al.ext)
  (export '%al.ext::+soft-output-limiter+ :%al.ext)
  (export '%al.ext::+reverb-default-decay-hflimit+ :%al.ext)
  (export '%al.ext::+ring-modulator-sawtooth+ :%al.ext)
  (export '%al.ext::+format-quad16+ :%al.ext)
  (export '%al.ext::+reverb-max-decay-hflimit+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-late-reverb-delay+ :%al.ext)
  (export '%al.ext::+autowah-max-resonance+ :%al.ext)
  (export '%al.ext::+format-stereo-alaw+ :%al.ext)
  (export '%al.ext::+echo-min-feedback+ :%al.ext)
  (export '%al.ext::+reverb-preset-outdoors-valley+ :%al.ext)
  (export '%al.ext::+reverb-default-decay-hfratio+ :%al.ext)
  (export '%al.ext::+reverb-preset-driving-incar-racer+ :%al.ext)
  (export '%al.ext::+flanger-phase+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-modulation-time+ :%al.ext)
  (export '%al.ext::+effect-autowah+ :%al.ext)
  (export '%al.ext::+reverb-max-late-reverb-gain+ :%al.ext)
  (export '%al.ext::+max-meters-per-unit+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-echo-time+ :%al.ext)
  (export '%al.ext::+reverb-preset-chapel+ :%al.ext)
  (export '%al.ext::+foldback-event-stop+ :%al.ext)
  (export '%al.ext::+soft-gain-clamp-ex+ :%al.ext)
  (export '%al.ext::+distortion-min-edge+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-gainlf+ :%al.ext)
  (export '%al.ext::+reverb-preset-icepalace-courtyard+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-ae+ :%al.ext)
  (export '%al.ext::+echo-feedback+ :%al.ext)
  (export '%al.ext::+ext-mulaw-mcformats+ :%al.ext)
  (export '%al.ext::+float+ :%al.ext)
  (export '%al.ext::+ext-double+ :%al.ext)
  (export '%al.ext::+pitch-shifter-default-coarse-tune+ :%al.ext)
  (export '%al.ext::+mono+ :%al.ext)
  (export '%al.ext::+effectslot-null+ :%al.ext)
  (export '%al.ext::+ring-modulator-sinusoid+ :%al.ext)
  (export '%al.ext::+reverb-preset-spacestation-cupboard+ :%al.ext)
  (export '%al.ext::+eaxreverb-hfreference+ :%al.ext)
  (export '%al.ext::+reverb-preset-spacestation-largeroom+ :%al.ext)
  (export '%al.ext::+frequency-shifter-max-right-direction+ :%al.ext)
  (export '%al.ext::+soft-direct-channels-remix+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-decay-hflimit+ :%al.ext)
  (export '%al.ext::+eaxreverb-gainlf+ :%al.ext)
  (export '%al.ext::+reverb-min-decay-time+ :%al.ext)
  (export '%al.ext::+ring-modulator-min-highpass-cutoff+ :%al.ext)
  (export '%al.ext::+format-61chn32+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-hfreference+ :%al.ext)
  (export '%al.ext::+unsigned-int+ :%al.ext)
  (export '%al.ext::+sample-length+ :%al.ext)
  (export '%al.ext::+sec-offset-clock+ :%al.ext)
  (export '%al.ext::+filter-null+ :%al.ext)
  (export '%al.ext::+effectslot-gain+ :%al.ext)
  (export '%al.ext::+frequency-shifter-default-frequency+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-decay-time+ :%al.ext)
  (export '%al.ext::+reverb-preset-forest+ :%al.ext)
  (export '%al.ext::+reverb-default-gain+ :%al.ext)
  (export '%al.ext::+flanger-min-rate+ :%al.ext)
  (export '%al.ext::+reverb-preset-paddedcell+ :%al.ext)
  (export '%al.ext::+int+ :%al.ext)
  (export '%al.ext::+hrtf-denied+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-late-reverb-gain+ :%al.ext)
  (export '%al.ext::+stereo32f+ :%al.ext)
  (export '%al.ext::+distortion-default-lowpass-cutoff+ :%al.ext)
  (export '%al.ext::+distortion-max-edge+ :%al.ext)
  (export '%al.ext::+highpass-gain+ :%al.ext)
  (export '%al.ext::+chorus-waveform-triangle+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-eh+ :%al.ext)
  (export '%al.ext::+reverb-preset-factory-longpassage+ :%al.ext)
  (export '%al.ext::+lowpass-gainhf+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-gainlf+ :%al.ext)
  (export '%al.ext::+chorus-min-feedback+ :%al.ext)
  (export '%al.ext::+equalizer-max-mid2-width+ :%al.ext)
  (export '%al.ext::+reverb-preset-quarry+ :%al.ext)
  (export '%al.ext::+reverb-preset-wooden-courtyard+ :%al.ext)
  (export '%al.ext::+reverb-preset-icepalace-hall+ :%al.ext)
  (export '%al.ext::+frequency-shifter-default-right-direction+
          :%al.ext)
  (export '%al.ext::+internal-format+ :%al.ext)
  (export '%al.ext::+ext-efx-name+ :%al.ext)
  (export '%al.ext::+connected+ :%al.ext)
  (export '%al.ext::+reverb-preset-factory-mediumroom+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-reflections-pan-xyz+ :%al.ext)
  (export '%al.ext::+hrtf-id+ :%al.ext)
  (export '%al.ext::+7point1-16+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-diffusion+ :%al.ext)
  (export '%al.ext::+reverb-preset-wooden-mediumroom+ :%al.ext)
  (export '%al.ext::+reverb-preset-prefab-practiseroom+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-iy+ :%al.ext)
  (export '%al.ext::+ring-modulator-default-frequency+ :%al.ext)
  (export '%al.ext::+ext-mulaw-bformat+ :%al.ext)
  (export '%al.ext::+distortion-default-gain+ :%al.ext)
  (export '%al.ext::+frequency-shifter-max-frequency+ :%al.ext)
  (export '%al.ext::+autowah-max-attack-time+ :%al.ext)
  (export '%al.ext::+reverb-preset-spacestation-alcove+ :%al.ext)
  (export '%al.ext::+format-type+ :%al.ext)
  (export '%al.ext::+reverb-preset-castle-courtyard+ :%al.ext)
  (export '%al.ext::+chorus-min-rate+ :%al.ext)
  (export '%al.ext::+bandpass-default-gainhf+ :%al.ext)
  (export '%al.ext::+reverb-preset-driving-fullgrandstand+ :%al.ext)
  (export '%al.ext::+soft-block-alignment+ :%al.ext)
  (export '%al.ext::fl-lf-reference :%al.ext)
  (export '%al.ext::+filter-type+ :%al.ext)
  (export '%al.ext::+format-channels+ :%al.ext)
  (export '%al.ext::+vocal-morpher-min-rate+ :%al.ext)
  (export '%al.ext::+byte3+ :%al.ext)
  (export '%al.ext::+effect-type+ :%al.ext)
  (export '%al.ext::+flanger-waveform-sinusoid+ :%al.ext)
  (export '%al.ext::fl-late-reverb-pan :%al.ext)
  (export '%al.ext::+frequency-shifter-max-left-direction+ :%al.ext)
  (export '%al.ext::+pitch-shifter-max-fine-tune+ :%al.ext)
  (export '%al.ext::+echo-min-delay+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-b+ :%al.ext)
  (export '%al.ext::+reverb-preset-city-subway+ :%al.ext)
  (export '%al.ext::+dedicated-gain+ :%al.ext)
  (export '%al.ext::+bandpass-max-gainlf+ :%al.ext)
  (export '%al.ext::+stereo16+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-room-rolloff-factor+ :%al.ext)
  (export '%al.ext::+reverb-preset-castle-hall+ :%al.ext)
  (export '%al.ext::+flanger-rate+ :%al.ext)
  (export '%al.ext::+reverb-preset-spacestation-longpassage+
          :%al.ext)
  (export '%al.ext::+equalizer-mid2-gain+ :%al.ext)
  (export '%al.ext::+min-room-rolloff-factor+ :%al.ext)
  (export '%al.ext::fl-room-rolloff-factor :%al.ext)
  (export '%al.ext::+eaxreverb-min-reflections-delay+ :%al.ext)
  (export '%al.ext::+effect-last-parameter+ :%al.ext)
  (export '%al.ext::+format-stereo-msadpcm+ :%al.ext)
  (export '%al.ext::+reverb-preset-pipe-longthin+ :%al.ext)
  (export '%al.ext::+autowah-max-peak-gain+ :%al.ext)
  (export '%al.ext::+bandpass-min-gainlf+ :%al.ext)
  (export '%al.ext::+stereo-angles+ :%al.ext)
  (export '%al.ext::+cone-outer-gainhf+ :%al.ext)
  (export '%al.ext::+chorus-max-feedback+ :%al.ext)
  (export '%al.ext::+vocal-morpher-min-phonemea-coarse-tuning+
          :%al.ext)
  (export '%al.ext::+ring-modulator-max-highpass-cutoff+ :%al.ext)
  (export '%al.ext::+filter-bandpass+ :%al.ext)
  (export '%al.ext::fl-modulation-time :%al.ext)
  (export '%al.ext::+eaxreverb-default-decay-hflimit+ :%al.ext)
  (export '%al.ext::+event-callback-user-param+ :%al.ext)
  (export '%al.ext::+frequency-shifter-min-frequency+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-reflections-delay+ :%al.ext)
  (export '%al.ext::+chorus-default-depth+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-echo-depth+ :%al.ext)
  (export '%al.ext::+equalizer-max-mid1-width+ :%al.ext)
  (export '%al.ext::+distortion-max-lowpass-cutoff+ :%al.ext)
  (export '%al.ext::+reverb-reflections-gain+ :%al.ext)
  (export '%al.ext::+flanger-waveform-triangle+ :%al.ext)
  (export '%al.ext::+echo-default-damping+ :%al.ext)
  (export '%al.ext::+equalizer-mid1-center+ :%al.ext)
  (export '%al.ext::+reverb-preset-arena+ :%al.ext)
  (export '%al.ext::+format-61chn8+ :%al.ext)
  (export '%al.ext::+eaxreverb-echo-depth+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-modulation-depth+ :%al.ext)
  (export '%al.ext::+autowah-default-peak-gain+ :%al.ext)
  (export '%al.ext::+lowpass-max-gain+ :%al.ext)
  (export '%al.ext::+distortion-edge+ :%al.ext)
  (export '%al.ext::+remix-unmatched+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-g+ :%al.ext)
  (export '%al.ext::+default-filter-order+ :%al.ext)
  (export '%al.ext::+eaxreverb-reflections-delay+ :%al.ext)
  (export '%al.ext::+reverb-default-reflections-gain+ :%al.ext)
  (export '%al.ext::+reverb-default-air-absorption-gainhf+ :%al.ext)
  (export '%al.ext::+autowah-peak-gain+ :%al.ext)
  (export '%al.ext::+flanger-max-delay+ :%al.ext)
  (export '%al.ext::+ext-foldback-name+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-decay-lfratio+ :%al.ext)
  (export '%al.ext::+flanger-min-phase+ :%al.ext)
  (export '%al.ext::+reverb-preset-driving-commentator+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-modulation-time+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-density+ :%al.ext)
  (export '%al.ext::+reverb-min-decay-hfratio+ :%al.ext)
  (export '%al.ext::+reverb-preset-sport-emptystadium+ :%al.ext)
  (export '%al.ext::+default-cone-outer-gainhf+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-v+ :%al.ext)
  (export '%al.ext::+chorus-max-waveform+ :%al.ext)
  (export '%al.ext::+reverb-density+ :%al.ext)
  (export '%al.ext::+reverb-preset-city-underpass+ :%al.ext)
  (export '%al.ext::+frequency-shifter-frequency+ :%al.ext)
  (export '%al.ext::+reverb-max-reflections-gain+ :%al.ext)
  (export '%al.ext::+format-51chn-mulaw+ :%al.ext)
  (export '%al.ext::+auxiliary-send-filter-gainhf-auto+ :%al.ext)
  (export '%al.ext::+chan-main-loki+ :%al.ext)
  (export '%al.ext::+auto+ :%al.ext)
  (export '%al.ext::+reverb-preset-wooden-cupboard+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-ao+ :%al.ext)
  (export '%al.ext::+reverb-decay-hflimit+ :%al.ext)
  (export '%al.ext::+byte-rw-offsets+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-air-absorption-gainhf+
          :%al.ext)
  (export '%al.ext::fl-gain-lf :%al.ext)
  (export '%al.ext::+equalizer-max-mid1-gain+ :%al.ext)
  (export '%al.ext::+equalizer-max-mid2-center+ :%al.ext)
  (export '%al.ext::+chorus-max-phase+ :%al.ext)
  (export '%al.ext::+reverb-preset-wooden-smallroom+ :%al.ext)
  (export '%al.ext::+bandpass-default-gainlf+ :%al.ext)
  (export '%al.ext::+equalizer-min-mid2-gain+ :%al.ext)
  (export '%al.ext::+6point1+ :%al.ext)
  (export '%al.ext::+filter-last-parameter+ :%al.ext)
  (export '%al.ext::+mono32f+ :%al.ext)
  (export '%al.ext::+soft-effect-target+ :%al.ext)
  (export '%al.ext::+reverb-preset-alley+ :%al.ext)
  (export '%al.ext::+reverb-preset-icepalace-longpassage+ :%al.ext)
  (export '%al.ext::+effect-eaxreverb+ :%al.ext)
  (export '%al.ext::+soft-hrtf+ :%al.ext)
  (export '%al.ext::+reverb-preset-spacestation-hall+ :%al.ext)
  (export '%al.ext::+bandpass-gain+ :%al.ext)
  (export '%al.ext::+min-auxiliary-send-filter-gain-auto+ :%al.ext)
  (export '%al.ext::+format-quad-mulaw+ :%al.ext)
  (export '%al.ext::+quad8+ :%al.ext)
  (export '%al.ext::+reverb-preset-spacestation-mediumroom+ :%al.ext)
  (export '%al.ext::+format-bformat2d-mulaw+ :%al.ext)
  (export '%al.ext::+format-rear32+ :%al.ext)
  (export '%al.ext::event-callback :%al.ext)
  (export '%al.ext::+chan-pcm-loki+ :%al.ext)
  (export '%al.ext::+major-version+ :%al.ext)
  (export '%al.ext::+reverb-min-late-reverb-delay+ :%al.ext)
  (export '%al.ext::+hrtf-unsupported-format+ :%al.ext)
  (export '%al.ext::+vocal-morpher-default-phonemeb+ :%al.ext)
  (export '%al.ext::+frequency-shifter-direction-down+ :%al.ext)
  (export '%al.ext::+loki-wave-format+ :%al.ext)
  (export '%al.ext::+pitch-shifter-min-fine-tune+ :%al.ext)
  (export '%al.ext::+stereo+ :%al.ext)
  (export '%al.ext::+equalizer-min-mid1-width+ :%al.ext)
  (export '%al.ext::+distortion-default-eqcenter+ :%al.ext)
  (export '%al.ext::+loki-ima-adpcm-format+ :%al.ext)
  (export '%al.ext::+eaxreverb-gain+ :%al.ext)
  (export '%al.ext::+minor-version+ :%al.ext)
  (export '%al.ext::+effect-flanger+ :%al.ext)
  (export '%al.ext::+effect-chorus+ :%al.ext)
  (export '%al.ext::+reverb-preset-castle-largeroom+ :%al.ext)
  (export '%al.ext::+unpack-block-alignment+ :%al.ext)
  (export '%al.ext::+5point1-32f+ :%al.ext)
  (export '%al.ext::+format-71chn32+ :%al.ext)
  (export '%al.ext::+7point1-32f+ :%al.ext)
  (export '%al.ext::+equalizer-min-low-gain+ :%al.ext)
  (export '%al.ext::+eaxreverb-gainhf+ :%al.ext)
  (export '%al.ext::fl-diffusion :%al.ext)
  (export '%al.ext::+format-51chn32+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-decay-lfratio+ :%al.ext)
  (export '%al.ext::+foldback-mode-mono+ :%al.ext)
  (export '%al.ext::+echo-damping+ :%al.ext)
  (export '%al.ext::+max-air-absorption-factor+ :%al.ext)
  (export '%al.ext::+equalizer-low-cutoff+ :%al.ext)
  (export '%al.ext::+frequency-shifter-default-left-direction+
          :%al.ext)
  (export '%al.ext::+foldback-event-start+ :%al.ext)
  (export '%al.ext::+equalizer-max-mid1-center+ :%al.ext)
  (export '%al.ext::+flanger-waveform+ :%al.ext)
  (export '%al.ext::+reverb-min-diffusion+ :%al.ext)
  (export '%al.ext::|C:@SA@EFXEAXREVERBPROPERTIES| :%al.ext)
  (export '%al.ext::+vocal-morpher-waveform+ :%al.ext)
  (export '%al.ext::fl-echo-depth :%al.ext)
  (export '%al.ext::+compressor-default-onoff+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-modulation-depth+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-late-reverb-gain+ :%al.ext)
  (export '%al.ext::+byte-length+ :%al.ext)
  (export '%al.ext::+reverb-preset-icepalace-alcove+ :%al.ext)
  (export '%al.ext::+auxiliary-send-filter+ :%al.ext)
  (export '%al.ext::+reverb-preset-city-museum+ :%al.ext)
  (export '%al.ext::+unsigned-byte+ :%al.ext)
  (export '%al.ext::+reverb-preset-outdoors-deepcanyon+ :%al.ext)
  (export '%al.ext::+flanger-max-rate+ :%al.ext)
  (export '%al.ext::+reverb-default-decay-time+ :%al.ext)
  (export '%al.ext::+eaxreverb-late-reverb-delay+ :%al.ext)
  (export '%al.ext::+reverb-max-decay-hfratio+ :%al.ext)
  (export '%al.ext::+frequency-shifter-min-right-direction+ :%al.ext)
  (export '%al.ext::+ext-vorbis+ :%al.ext)
  (export '%al.ext::+reverb-preset-factory-largeroom+ :%al.ext)
  (export '%al.ext::+soft-loopback+ :%al.ext)
  (export '%al.ext::+flanger-depth+ :%al.ext)
  (export '%al.ext::+eaxreverb-diffusion+ :%al.ext)
  (export '%al.ext::+reverb-preset-wooden-longpassage+ :%al.ext)
  (export '%al.ext::fl-echo-time :%al.ext)
  (export '%al.ext::+compressor-min-onoff+ :%al.ext)
  (export '%al.ext::+device-clock-latency+ :%al.ext)
  (export '%al.ext::fl-reflections-delay :%al.ext)
  (export '%al.ext::+device-clock+ :%al.ext)
  (export '%al.ext::+equalizer-default-mid1-center+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-er+ :%al.ext)
  (export '%al.ext::+eaxreverb-reflections-gain+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-diffusion+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-decay-hfratio+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-hfreference+ :%al.ext)
  (export '%al.ext::+reverb-max-density+ :%al.ext)
  (export '%al.ext::+format-mono-msadpcm+ :%al.ext)
  (export '%al.ext::+echo-lrdelay+ :%al.ext)
  (export '%al.ext::+equalizer-mid2-width+ :%al.ext)
  (export '%al.ext::+chorus-rate+ :%al.ext)
  (export '%al.ext::+min-auxiliary-send-filter-gainhf-auto+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-r+ :%al.ext)
  (export '%al.ext::+flanger-max-feedback+ :%al.ext)
  (export '%al.ext::+reverb-preset-bathroom+ :%al.ext)
  (export '%al.ext::+presets-h+ :%al.ext)
  (export '%al.ext::+flanger-default-delay+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-m+ :%al.ext)
  (export '%al.ext::+soft-pause-device+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phonemea-coarse-tuning+ :%al.ext)
  (export '%al.ext::+format-bformat3d-8+ :%al.ext)
  (export '%al.ext::+vocal-morpher-default-phonemea-coarse-tuning+
          :%al.ext)
  (export '%al.ext::+5point1-16+ :%al.ext)
  (export '%al.ext::+reverb-room-rolloff-factor+ :%al.ext)
  (export '%al.ext::+equalizer-high-cutoff+ :%al.ext)
  (export '%al.ext::+reverb-preset-prefab-schoolroom+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-density+ :%al.ext)
  (export '%al.ext::+equalizer-min-mid2-width+ :%al.ext)
  (export '%al.ext::+chorus-default-phase+ :%al.ext)
  (export '%al.ext::+reverb-default-late-reverb-delay+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-reflections-gain+ :%al.ext)
  (export '%al.ext::+chorus-max-depth+ :%al.ext)
  (export '%al.ext::uint64 :%al.ext)
  (export '%al.ext::+ext-disconnect+ :%al.ext)
  (export '%al.ext::+equalizer-default-mid1-gain+ :%al.ext)
  (export '%al.ext::+distortion-default-eqbandwidth+ :%al.ext)
  (export '%al.ext::+ambisonic-order+ :%al.ext)
  (export '%al.ext::+source-radius+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-decay-time+ :%al.ext)
  (export '%al.ext::+stereo8+ :%al.ext)
  (export '%al.ext::+eaxreverb-density+ :%al.ext)
  (export '%al.ext::+autowah-default-resonance+ :%al.ext)
  (export '%al.ext::+format-61chn-mulaw+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-reflections-gain+ :%al.ext)
  (export '%al.ext::+flanger-default-depth+ :%al.ext)
  (export '%al.ext::+reverb-min-reflections-gain+ :%al.ext)
  (export '%al.ext::+ring-modulator-min-frequency+ :%al.ext)
  (export '%al.ext::+ext-efx+ :%al.ext)
  (export '%al.ext::+reverb-preset-spacestation-smallroom+ :%al.ext)
  (export '%al.ext::i-decay-hf-limit :%al.ext)
  (export '%al.ext::+eaxreverbproperties-defined+ :%al.ext)
  (export '%al.ext::+equalizer-max-high-cutoff+ :%al.ext)
  (export '%al.ext::+format-wave+ :%al.ext)
  (export '%al.ext::+min-air-absorption-factor+ :%al.ext)
  (export '%al.ext::+mono8+ :%al.ext)
  (export '%al.ext::+reverb-preset-factory-hall+ :%al.ext)
  (export '%al.ext::+flanger-max-depth+ :%al.ext)
  (export '%al.ext::+equalizer-default-low-gain+ :%al.ext)
  (export '%al.ext::+pitch-shifter-min-coarse-tune+ :%al.ext)
  (export '%al.ext::+max-direct-filter-gainhf-auto+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-modulation-depth+ :%al.ext)
  (export '%al.ext::+eaxreverb-decay-lfratio+ :%al.ext)
  (export '%al.ext::+flanger-min-delay+ :%al.ext)
  (export '%al.ext::+echo-delay+ :%al.ext)
  (export '%al.ext::+reverb-preset-dizzy+ :%al.ext)
  (export '%al.ext::+fuma+ :%al.ext)
  (export '%al.ext::+autowah-default-release-time+ :%al.ext)
  (export '%al.ext::+vocal-morpher-min-phonemeb-coarse-tuning+
          :%al.ext)
  (export '%al.ext::+autowah-max-release-time+ :%al.ext)
  (export '%al.ext::+soft-source-latency+ :%al.ext)
  (export '%al.ext::+pitch-shifter-coarse-tune+ :%al.ext)
  (export '%al.ext::+event-type-disconnected+ :%al.ext)
  (export '%al.ext::+reverb-preset-sport-smallswimmingpool+ :%al.ext)
  (export '%al.ext::+reverb-preset-factory-shortpassage+ :%al.ext)
  (export '%al.ext::+soft-bformat-ex+ :%al.ext)
  (export '%al.ext::+distortion-gain+ :%al.ext)
  (export '%al.ext::+ring-modulator-frequency+ :%al.ext)
  (export '%al.ext::+reverb-preset-factory-smallroom+ :%al.ext)
  (export '%al.ext::+default-meters-per-unit+ :%al.ext)
  (export '%al.ext::+echo-max-feedback+ :%al.ext)
  (export '%al.ext::int64 :%al.ext)
  (export '%al.ext::+equalizer-high-gain+ :%al.ext)
  (export '%al.ext::+ring-modulator-default-waveform+ :%al.ext)
  (export '%al.ext::+ambisonic-scaling+ :%al.ext)
  (export '%al.ext::+reverb-preset-icepalace-largeroom+ :%al.ext)
  (export '%al.ext::+equalizer-default-high-gain+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-ah+ :%al.ext)
  (export '%al.ext::+reverb-preset-auditorium+ :%al.ext)
  (export '%al.ext::+format-stereo-ima4+ :%al.ext)
  (export '%al.ext::+6point1-8+ :%al.ext)
  (export '%al.ext::+bandpass-default-gain+ :%al.ext)
  (export '%al.ext::+distortion-min-lowpass-cutoff+ :%al.ext)
  (export '%al.ext::+chorus-phase+ :%al.ext)
  (export '%al.ext::+reverb-preset-dome-saintpauls+ :%al.ext)
  (export '%al.ext::+vocal-morpher-min-phonemeb+ :%al.ext)
  (export '%al.ext::+reverb-min-reflections-delay+ :%al.ext)
  (export '%al.ext::+ring-modulator-max-frequency+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-j+ :%al.ext)
  (export '%al.ext::+reverb-max-air-absorption-gainhf+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-ih+ :%al.ext)
  (export '%al.ext::+acn+ :%al.ext)
  (export '%al.ext::+equalizer-mid1-gain+ :%al.ext)
  (export '%al.ext::+hrtf-disabled+ :%al.ext)
  (export '%al.ext::+effect-first-parameter+ :%al.ext)
  (export '%al.ext::+soft-msadpcm+ :%al.ext)
  (export '%al.ext::+reverb-decay-time+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-gainhf+ :%al.ext)
  (export '%al.ext::+chorus-max-rate+ :%al.ext)
  (export '%al.ext::+reverb-preset-cave+ :%al.ext)
  (export '%al.ext::+effect-frequency-shifter+ :%al.ext)
  (export '%al.ext::+format-mono-ima4+ :%al.ext)
  (export '%al.ext::+6point1-32f+ :%al.ext)
  (export '%al.ext::+room-rolloff-factor+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-room-rolloff-factor+ :%al.ext)
  (export '%al.ext::+chorus-delay+ :%al.ext)
  (export '%al.ext::+reverb-preset-icepalace-cupboard+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-n+ :%al.ext)
  (export '%al.ext::+effect-dedicated-low-frequency-effect+ :%al.ext)
  (export '%al.ext::+6point1-16+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-gainlf+ :%al.ext)
  (export '%al.ext::+reverb-preset-spacestation-shortpassage+
          :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-s+ :%al.ext)
  (export '%al.ext::+reverb-min-room-rolloff-factor+ :%al.ext)
  (export '%al.ext::+highpass-default-gain+ :%al.ext)
  (export '%al.ext::+direct-channels+ :%al.ext)
  (export '%al.ext::+lowpass-min-gain+ :%al.ext)
  (export '%al.ext::+filter-highpass+ :%al.ext)
  (export '%al.ext::+bformat3d+ :%al.ext)
  (export '%al.ext::+reverb-preset-mood-hell+ :%al.ext)
  (export '%al.ext::+autowah-min-peak-gain+ :%al.ext)
  (export '%al.ext::+reverb-default-reflections-delay+ :%al.ext)
  (export '%al.ext::+reverb-late-reverb-delay+ :%al.ext)
  (export '%al.ext::+vocal-morpher-default-phonemea+ :%al.ext)
  (export '%al.ext::+soft-buffer-sub-data+ :%al.ext)
  (export '%al.ext::+reverb-preset-factory-cupboard+ :%al.ext)
  (export '%al.ext::+reverb-preset-prefab-workshop+ :%al.ext)
  (export '%al.ext::eaxreverbproperties :%al.ext)
  (export '%al.ext::+ext-bformat+ :%al.ext)
  (export '%al.ext::+chorus-default-waveform+ :%al.ext)
  (export '%al.ext::+distortion-eqbandwidth+ :%al.ext)
  (export '%al.ext::+reverb-preset-drugged+ :%al.ext)
  (export '%al.ext::+vocal-morpher-rate+ :%al.ext)
  (export '%al.ext::+reverb-max-decay-time+ :%al.ext)
  (export '%al.ext::+reverb-preset-hangar+ :%al.ext)
  (export '%al.ext::+reverb-max-diffusion+ :%al.ext)
  (export '%al.ext::+pitch-shifter-max-coarse-tune+ :%al.ext)
  (export '%al.ext::+frequency-shifter-direction-off+ :%al.ext)
  (export '%al.ext::+chorus-depth+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-gainhf+ :%al.ext)
  (export '%al.ext::+bandpass-max-gainhf+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-gain+ :%al.ext)
  (export '%al.ext::+reverb-preset-outdoors-creek+ :%al.ext)
  (export '%al.ext::+format-rear-mulaw+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-diffusion+ :%al.ext)
  (export '%al.ext::+autowah-resonance+ :%al.ext)
  (export '%al.ext::+highpass-max-gain+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-density+ :%al.ext)
  (export '%al.ext::+autowah-attack-time+ :%al.ext)
  (export '%al.ext::+chorus-default-rate+ :%al.ext)
  (export '%al.ext::+vocal-morpher-max-phonemeb-coarse-tuning+
          :%al.ext)
  (export '%al.ext::+eaxreverb-max-reflections-gain+ :%al.ext)
  (export '%al.ext::+vocal-morpher-max-rate+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-d+ :%al.ext)
  (export '%al.ext::+echo-default-lrdelay+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-echo-depth+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-l+ :%al.ext)
  (export '%al.ext::+highpass-min-gainlf+ :%al.ext)
  (export '%al.ext::+reverb-preset-pipe-large+ :%al.ext)
  (export '%al.ext::+reverb-preset-castle-longpassage+ :%al.ext)
  (export '%al.ext::+n3d+ :%al.ext)
  (export '%al.ext::+autowah-min-attack-time+ :%al.ext)
  (export '%al.ext::+effectslot-auxiliary-send-auto+ :%al.ext)
  (export '%al.ext::+min-direct-filter-gainhf-auto+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-air-absorption-gainhf+ :%al.ext)
  (export '%al.ext::+distortion-min-eqcenter+ :%al.ext)
  (export '%al.ext::+flanger-delay+ :%al.ext)
  (export '%al.ext::+quad+ :%al.ext)
  (export '%al.ext::fl-reflections-pan :%al.ext)
  (export '%al.ext::+ring-modulator-highpass-cutoff+ :%al.ext)
  (export '%al.ext::+gain-limit+ :%al.ext)
  (export '%al.ext::+max-auxiliary-send-filter-gainhf-auto+ :%al.ext)
  (export '%al.ext::eventproc :%al.ext)
  (export '%al.ext::+reverb-preset-carpetedhallway+ :%al.ext)
  (export '%al.ext::+effect-reverb+ :%al.ext)
  (export '%al.ext::+reverb-preset-wooden-largeroom+ :%al.ext)
  (export '%al.ext::+distortion-default-edge+ :%al.ext)
  (export '%al.ext::+reverb-preset-icepalace-smallroom+ :%al.ext)
  (export '%al.ext::+reverb-preset-sport-stadiumtannoy+ :%al.ext)
  (export '%al.ext::+ext-dedicated+ :%al.ext)
  (export '%al.ext::+format-bformat2d-float32+ :%al.ext)
  (export '%al.ext::+vocal-morpher-max-phonemeb+ :%al.ext)
  (export '%al.ext::+vocal-morpher-phoneme-u+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-echo-time+ :%al.ext)
  (export '%al.ext::+loki-audio-channel+ :%al.ext)
  (export '%al.ext::+eaxreverb-modulation-time+ :%al.ext)
  (export '%al.ext::+reverb-preset-icepalace-mediumroom+ :%al.ext)
  (export '%al.ext::fl-late-reverb-delay :%al.ext)
  (export '%al.ext::+default-direct-filter-gainhf-auto+ :%al.ext)
  (export '%al.ext::+reverb-decay-hfratio+ :%al.ext)
  (export '%al.ext::+reverb-preset-castle-alcove+ :%al.ext)
  (export '%al.ext::+bandpass-gainlf+ :%al.ext)
  (export '%al.ext::+lowpass-default-gain+ :%al.ext)
  (export '%al.ext::+flanger-min-depth+ :%al.ext)
  (export '%al.ext::+vocal-morpher-waveform-triangle+ :%al.ext)
  (export '%al.ext::+eaxreverb-max-decay-hflimit+ :%al.ext)
  (export '%al.ext::+reverb-min-gainhf+ :%al.ext)
  (export '%al.ext::+equalizer-default-high-cutoff+ :%al.ext)
  (export '%al.ext::+pitch-shifter-default-fine-tune+ :%al.ext)
  (export '%al.ext::+hrtf-required+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-lfreference+ :%al.ext)
  (export '%al.ext::+flanger-max-phase+ :%al.ext)
  (export '%al.ext::+eaxreverb-lfreference+ :%al.ext)
  (export '%al.ext::+format-stereo-double+ :%al.ext)
  (export '%al.ext::+ext-h+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-gain+ :%al.ext)
  (export '%al.ext::+reverb-preset-hallway+ :%al.ext)
  (export '%al.ext::+eaxreverb-min-late-reverb-gain+ :%al.ext)
  (export '%al.ext::+format-stereo-mulaw+ :%al.ext)
  (export '%al.ext::+equalizer-default-mid2-center+ :%al.ext)
  (export '%al.ext::+flanger-max-waveform+ :%al.ext)
  (export '%al.ext::+event-callback-function+ :%al.ext)
  (export '%al.ext::+reverb-preset-driving-incar-sports+ :%al.ext)
  (export '%al.ext::+sample-offset-clock+ :%al.ext)
  (export '%al.ext::+meters-per-unit+ :%al.ext)
  (export '%al.ext::+chorus-default-feedback+ :%al.ext)
  (export '%al.ext::+eaxreverb-default-decay-hfratio+ :%al.ext)
  (export '%al.ext::+quad16+ :%al.ext)
  (export '%al.ext::+soft-buffer-samples+ :%al.ext)
  (export '%al.ext::+vocal-morpher-default-waveform+ :%al.ext)
  (export '%al.ext::+sec-length+ :%al.ext)
  (export '%al.ext::+short+ :%al.ext))

